MODULE PARAMS
  IMPLICIT NONE
  INTEGER, PARAMETER :: KR=111         !MAX DIMENSION OF CORE
  INTEGER, PARAMETER :: KX=105, KY=55  !MAX DIMENSIONS OF SOL
                       !KX=51, KY=42   !IN COREDIV
  INTEGER, PARAMETER :: KX1=KX+1, KY1=KY+1
  INTEGER, PARAMETER :: IG=5           !MAX NEUTRAL GROUPS
  INTEGER, PARAMETER :: KIM=5, KZ=88   !MAX NO. OF IMPURITIES AND IONIZATION STATES
!  USED IN COREDIV
  INTEGER, PARAMETER :: KH3=1001, KH4=10  !KH1=5
  INTEGER, PARAMETER :: KHT=8000, KHB=500, KHC=20
!  USED IN TECXY
  integer, parameter :: KT1=200,KT2=20000
  integer, parameter :: IDT=500
                       
  !INTEGER, PARAMETER :: NDWNLFLS = 18   ! NOT USED CURRENTLY
  INTEGER, PARAMETER :: SNS=42, BFS=1000, HDS=500  !SNS NOT USED NOW
  INTEGER, PARAMETER :: KS1=30, KS2=90
!    EMPIRICAL B-BGB COEFFICIENTS FOR BGBTRANSPORT
  DOUBLE PRECISION, PARAMETER :: BB_E= 8.0E-5
  DOUBLE PRECISION, PARAMETER :: BB_I= 1.6E-4
  DOUBLE PRECISION, PARAMETER :: BGB_E=1.75E-2
  DOUBLE PRECISION, PARAMETER :: BGB_I=3.50E-2
!    CONSTANT FRACTIONS IN PHYSPUT
  DOUBLE PRECISION, PARAMETER :: PWR1BY6 = 1.0D0 / 6.0D0
  DOUBLE PRECISION, PARAMETER :: PWR5BY6 = 5.0D0 / 6.0D0
  DOUBLE PRECISION, PARAMETER :: PWR1BY3 = 1.0D0 / 3.0D0
  DOUBLE PRECISION, PARAMETER :: PWR2BY3 = 2.0D0 / 3.0D0
!    CONTROL INDEX FOR CONVERGENCE CHECK
  integer, PARAMETER:: INDEX2=36  !NO OF PARAMS FOR PLASMA CONVERGENCE CHECK
END MODULE PARAMS

MODULE CONSTANTS
  IMPLICIT NONE
  DOUBLE PRECISION, PARAMETER :: PI    =3.14159265358979323846
  DOUBLE PRECISION, PARAMETER :: NA2PI =0.15915494309189533577 !0.5D0/PI
  DOUBLE PRECISION, PARAMETER :: PI2   =1.57079632679489661923 !0.5PI
  DOUBLE PRECISION, PARAMETER :: EE    =2.71828182845904523536
  DOUBLE PRECISION, PARAMETER :: EC    =1.602176634E-19
  DOUBLE PRECISION, PARAMETER :: XMIU0 = PI*4.E-7
  DOUBLE PRECISION, PARAMETER :: EH    =17.6                   !SHOULDN'T BE 13.59844 eV?
  DOUBLE PRECISION, PARAMETER :: PMASS =1.672621778E-27
  DOUBLE PRECISION, PARAMETER :: EMASS =9.1093837015E-31  !FORMER XEM !MASA ELEKTRONU (KG)
  DOUBLE PRECISION, PARAMETER :: AMASA(92) =[  1.007940,  4.002602,  6.941000,  9.012182,&
          10.811000, 12.011000, 14.006740, 15.999400, 18.9984032,20.179700,&
          22.989768, 24.3050,   26.981539, 28.0855,   30.973762, 32.066,   &
          35.4527,   39.948,    39.0983,   40.078,    44.955910, 47.88,    &
          50.9415,   51.9961,   54.93805,  55.847,    58.93320,  58.6934,  &
          63.546,    65.39,     69.723,    72.61,     74.92159,  78.96,    &
          79.904,    83.80,     85.4678,   87.62,     88.90585,  91.224,   &
          92.90638,  95.94,     98.,      101.07,    102.90550, 106.42,    &
         107.8682,  112.411,   114.82,    118.7107,  121.757,   127.603,   &
         126.90447, 131.29,    132.90543, 137.327,   138.9055,  140.115,   &
         140.90765, 144.24,    145.,      150.36,    151.965,   157.25,    &
         158.92534, 162.50,    164.93032, 167.26,    168.93421, 173.04,    &
         174.967,   178.49,    180.9479,  183.85,    186.207,   190.2,     &
         192.22,    195.08,    196.96654, 200.59,    204.3833,  207.2,     &
         208.98037, 209.,      210.,      222.,      223.,      226.025,   &
		 227.028,   232.0381,  231.0359,  238.0289 ]
  DOUBLE PRECISION, PARAMETER :: AREACT(7) =[5.65718E-12, 3.41267E-3, 1.99167E-3, &
         0.0, 1.05060E-5, 0.0, 0.0]
  DOUBLE PRECISION, PARAMETER :: BG    =31.3970
  DOUBLE PRECISION, PARAMETER :: XMC   =937814.0
  DOUBLE PRECISION, PARAMETER :: PJON(3) =[13.6,13.6,13.6]
  !SPUTER_LI
  DOUBLE PRECISION, PARAMETER :: AVON  =0.60221
  !SURFACE BINDING ENERGY (HEAT OF SUBLIMATION) [EV]
  DOUBLE PRECISION, PARAMETER :: ES(92)=[0.,0.,1.63,3.32,5.77,7.37,0.,0.,0.,0.,&
                                         0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,4.28,0.,0.,0.,0.,&
										 0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,3.14,&
										 0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,&
										 0.,0.,0.,8.68,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.]
  !DENSITY OF ELEMENTS  [G/CM^3]
  DOUBLE PRECISION, PARAMETER :: DEN(92)=[0.089,0.179,0.53,1.85,2.34,2.267,0.,0.,0.,0.,&
                                         0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,7.874,0.,0.,0.,0.,&
										 0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,7.31,&
										 0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,&
										 0.,0.,0.,19.29,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.]
  DOUBLE PRECISION, PARAMETER :: HMASA(3) =[1.007940, 2.01410177811, 3.0160492]
  !SPUTER_LI_TH
  DOUBLE PRECISION, PARAMETER :: KBKEV=8.617333262145E-5     !BOLTZMANN CONSTANT IN EV/K
  DOUBLE PRECISION, PARAMETER :: KB=1.38064852D-23           !Boltzman constant [m*m*kg/K/s/s]
  DOUBLE PRECISION, PARAMETER :: TROOM=298.15                !ROOM TEMPERATURE IN K
  DOUBLE PRECISION, PARAMETER :: LI_TMEBO(2)=[453.65,1603.0] !Li melting and boiling point
  DOUBLE PRECISION, PARAMETER :: EVAPLI=2.2583D-19           !Li enthalpy of evaporation in J per molecule
  DOUBLE PRECISION, PARAMETER :: SN_TMEBO(2)=[505.08,2875.0] !Sn melting and boiling point
  DOUBLE PRECISION, PARAMETER :: EVAPSN=4.9168D-19           !Sn enthalpy of evaporation in J per molecule
  !THERMCOND
  DOUBLE PRECISION, PARAMETER :: LLI(0:2)=[21.6318946932D0,0.0516087275899D0,-1.32802055988D-05]  !thermal conductivity polynomial fit coefficients for lithium
  DOUBLE PRECISION, PARAMETER :: LSN(0:1)=[20.0030204829D0,0.0204611835682D0]  !thermal conductivity polynomial fit coefficients for tin
  DOUBLE PRECISION, PARAMETER :: LW(0:4)=[5.4446338168D0,-0.121280474748D0,0.0072856920999D0,-0.000211152719785D0,2.28219321658D-06]  !thermal conductivity polynomial fit coefficients for tungsten

END MODULE

MODULE FILEPATHS
  INTEGER, PARAMETER :: LLEN=100  !length of filename
  CHARACTER :: DLM
  CHARACTER(LLEN) :: pathIparM  != "./results/IPAR_MAIN.DAT"
  CHARACTER(LLEN) :: pathTopwyn != "./results/TOPWYN.DAT"
  CHARACTER(LLEN) :: pathIter   != "./results/ITERATION.DAT"
  !CHARACTER(LLEN) :: pathIparCr != "./results/IPARCORE_EXT.DAT" !NOT USED
  !CHARACTER(LLEN) :: pathIparCB != "./results/IPARCORE_BIS.DAT"
  CHARACTER(LLEN) :: pathInptCr != "./results/INPUTCORE_N.DAT"
  CHARACTER(LLEN) :: pathInptSl != "./results/INPUTSOL.DAT"     !NOT USED
  !CHARACTER(LLEN) :: pathIparSl != "./results/IPARSOL_N.DAT"
  !CHARACTER(LLEN) :: pathIparSB != "./results/IPARSOL_BIS.DAT"
  CHARACTER(LLEN) :: pathWyn2D  != "./results/WYNIK2D.DAT"
  CHARACTER(LLEN) :: pathEvol2D != "./results/EVOL2D.DAT"
  CHARACTER(LLEN) :: pathRprofi != "./results/PROFILES.DAT"
  CHARACTER(LLEN) :: pathBfile  != "./results/BFILE"
  !CHARACTER(LLEN) :: pathProf   != "./results/INITPROF.DAT"    !CURRENTLY COMMENTED
  CHARACTER(LLEN) :: pathSOLTX
  CHARACTER(LLEN) :: meshpath   !".\results\DEMO_MESH_SN.DAT"
  CHARACTER(LLEN) :: pathTexWyn !".\results\TEXWYNIK.DAT"
  CHARACTER(LLEN) :: pathTexDat !".\results\TEXIDAT.DAT"
  CHARACTER(LLEN) :: pathTexDry !".\results\TEXDRYF.DAT"
  CHARACTER(LLEN) :: pathTexEvo !".\results\TEXEVOL.DAT"
  
  !from TECXY (read in READF_PATHS from IPATHS.DAT file)
  !character*100   :: rundir     !".\results\"
  character(LLEN)   :: atomdir    !"D:\Users\galazka\Programowanie\ATOMDATA\"
  character(LLEN)   :: meshdir    !".\results\"
  !character*100   :: dwnloaddir !".\results\profiles\"
END MODULE FILEPATHS

MODULE FUNITS
  INTEGER :: UEV2D, UTOPW, UITER, UWY2D, UXWYN
  INTEGER :: UTXSOL  !MIGHT BE OBSOLETE
END MODULE FUNITS

MODULE IMPDAT
  USE PARAMS
  IMPLICIT NONE
  INTEGER::    NOIM        !READ FROM IPARCORE IN INPUT (= NAIM)
  INTEGER::    LSTCIM(KIM) !LSTCI = LSTNN      ATOMIC NO. - MAXIMUM CHARGE (Z)
  INTEGER::    LSTTIM(KIM)    !=LST IN INPUTB, =LST IN BRZEG  TABLE WITH MAXIMUM CALCULATED Z FOR EACH IMPURITY
  REAL::       AMIM(KIM)   !AMZI  = AMZZ       MASS IN U
  REAL::       ZMIM(KIM)   !ZMI   = ZMM        MASS IN KG
  REAL::       RECIM(KIM)  ! -      ZRECYCC    RECYCLING COEFFICIENT
  INTEGER::    TYPIM(KIM)  ! -      IMTYPE     TYPE OF THE IMPURITY (DIVERTOR/SEEDED/HELIUM)
  real::       CONCZ(KIM)  !IMPURITY CONCENTRATION IN SOL/TECXY
END MODULE

MODULE PLASMADAT
  USE PARAMS
  IMPLICIT NONE
  REAL::     AMU   !=2.0        IN INPUT (FROM SCLR)
  REAL::     XMI   !=AMU*PMASS  IN INPUT
  REAL::     WD    !=1.         IN INPUT
  REAL::     HD    !=1.0        IN INPUT
  REAL::     ISOTFR(3)         !isotope fraction H/D/T
  REAL::     TE0   !=5.0E3      IN INPUT
  REAL::     TI0   !=5.0E3      IN INPUT
  REAL::     CONCHE  !=0.       IN INPUT
  REAL::     GT0    !=5.        IN INPUT (temperature of neutrals in the core)
  REAL::     BP0    !=2.E-7     IN INPUT (BP FACTOR)
END MODULE

MODULE STER !more CORE-like
  IMPLICIT NONE
  INTEGER::  ICONT
  INTEGER::  SOLCONT
  INTEGER::  IT_NUMB   !READ FROM IPARCORE IN INPUT
  !INTEGER::  LTI         !=IT_STEPS   IN MAIN, BEFORE BRZEG
  INTEGER::  IDLINE      !=0          IN INPUT
  INTEGER::  IVAPOR      !=0          IN INPUT
  INTEGER::  IPROMPT     !=0          IN INPUT
  INTEGER::  IFLUX0      !=1          IN INPUT
  INTEGER::  ISHIFT      !=0          IN INPUT
  INTEGER::  BCCORE      !   USED IN ONE_IMP_SOLV
  REAL::     GHT      !=0.01     IN INPUT, =HTMIN*REL IN TSTEP,   =HTMIN*WSPHT IN TSTEPNI
  REAL::     GWKR
  REAL::     GTIME    !CORE TIME
  REAL::     STIME    !SOL TIME
  INTEGER::  NTI      !READ FROM IPARCORE IN INPUT
  INTEGER::  NNI      !READ FROM IPARCORE IN INPUT (MAXIMUM TIME STEPS)
  INTEGER::  NGP      !=8       IN INPUT
  INTEGER::  ITRAN    !=1 IN INPUT
  INTEGER::  ITAUE    !=9 IN INPUT
  !CORE NON-LINEAR ITERATIONS CONVERGENCE:
  REAL::     CON
  !GLOBAL CONVERGENCE PARAMETERS:
  REAL::     EPSP
  REAL::     EPSZ
  REAL::     XYEPSP
  REAL::     XYEPSZ
  !REAL::     ERROR
  !BISECTION CONVERGENCE PARAMETERS:
  INTEGER::  BITER
  REAL::     BEPS
  !PROGONKA_NEW CONTROL PARAMETER
  REAL*8 ::   PROGFACT
  !SOL CONTROL PARAMETERS:
  INTEGER::  SOLMOD    !SOL MODEL - TECXY/COREDIV
  INTEGER::  NESMOD    !WHAT IS NESEP CONTROL MECHANISM 0-NONE/1-RECYCLING/2-INPUT FLUX
  INTEGER::  INESOPT   !THE SETPOINT VALUE FOR NES: 0-STAGNATION POINT, OTHER-AVERAGE EL. DENSITY
  INTEGER::  INS_ITER  !EACH HOW MANY STEPS FOR CONTROLING NES
  INTEGER::  CZSMOD    !CONTROL IMPURITY CONCENTRATION AT SEPARATRIX?
  INTEGER::  ICZ_NO    !WHICH IMPURITY?
  REAL   ::  ICZ_VAL   !CONCENTRATION SETPOINT
  INTEGER::  ICZ_ITER  !EACH HOW MANY STEPS FOR CONTROLING CZ_SEP
  !DISPLAY AND SAVE PARAMETERS
  INTEGER:: MAINPRINT !FOR MAIN LOOP
  INTEGER:: ISAVE     !FOR MAIN LOOP
  INTEGER:: CORPRINT  !PRINTING FREQUENCY FOR CORE
  INTEGER:: SOLPRINT  !PRINTING FREQUENCY FOR BOTH SOL LOOPS
END MODULE

MODULE WARIANT !more SOL-like
  IMPLICIT NONE
  INTEGER::  SCONTP
  INTEGER::  SCONTI
  INTEGER::  IT_STEPS  !READ FROM IPARCORE IN INPUT - SHOULD BE READ IN INPUTB
  INTEGER::  INH         !READ FROM IPARSOL IN INPUTB
  INTEGER::  INZ         !READ FROM IPARSOL IN INPUTB
  !INTEGER::  IHF         !READ FROM IPARSOL IN INPUTB
  INTEGER::  ISTYPE      !READ FROM IPARSOL IN INPUTB, =IMTYP IN BRZEG, =1/=0 IN DENSITB, ZROBIC PORZADEK
  INTEGER::  KMAP      !READ FROM IPARSOL IN INPUTB
  INTEGER::  LWYD        !READ FROM IPARSOL IN INPUTB
  INTEGER::  LPP         !=2          IN INITIATE_SOL
  REAL::     FLIME     !=1.    IN INPUTB
  REAL::     FLIMI     !=1.    IN INPUTB
  REAL::     WKR       !READ FROM IPARSOL IN INPUTB
  REAL::     HT        !READ FROM IPARSOL IN INPUTB
  LOGICAL::  IOPNE    !=1/=0 IN INPUTB (READ INPUTSOL? - INIT1B - MAIN PLASMA)
  LOGICAL::  IOPNZ    !=1/=0 IN INPUTB (READ INPUTSOL? - INIT2  - IMPURITIES)END MODULE

  LOGICAL::  IOPNI
  LOGICAL::  IOPTE
  LOGICAL::  IOPTI
  LOGICAL::  IOPV
  LOGICAL::  IOPN0
  LOGICAL::  IOPNET   !CAN BE LOCAL
  LOGICAL::  IOPVZ
  LOGICAL::  IOPZEF
  integer::  IORIENT
  
  integer::  ISYM     !MOVED FROM WARIANT_MOD
  integer::  JCASE    !MOVED FROM WARIANT2_MOD
  
  INTEGER::  BCSEP     !BC AT THE SEPARATRIX
  INTEGER::  BCSEPZ    !BC AT THE SEPARATRIX FOR THE IMPURITIES
END MODULE

MODULE DEVICE !OK
  IMPLICIT NONE
  REAL::     DNEAV   !=DDNEAV IN INPUT
  REAL::     DNIAV   !=DNEAV IN INIT, =DNEAV-AVER IN ZZ1,
  REAL::     PADD
  REAL::     RT
  REAL::     RP
  REAL::     RS
  REAL::     BT
  REAL::     CTOT
  REAL::     ELONG
  REAL::     QS      !=DQS       FROM DINPUT IN INPUTB
  REAL::     HFACT   !READ FROM IPARCORE IN INPUT
  INTEGER::  ILZER   !=1         IN INPUTB
  REAL*8::   TAUEEMP !=0.0259 IN INPUT, EMPIRICAL ENERGY CONFINMENT TIME
END MODULE

MODULE EVOL !OK
  USE PARAMS
  IMPLICIT NONE
  INTEGER::  IEV         !=1 IN MAIN, BEGINNING
  REAL::     QEFLUX(KHT) !=WQTE  in CONTROLPOINT
  REAL::     QIFLUX(KHT) !=WQTI  in CONTROLPOINT
  REAL::     PFLUX(KHT)  !=STN   in CONTROLPOINT
  REAL::     EDNE(KHT)   !=DNES  in EVOLSTAT
  REAL::     EDNI(KHT)   !=DNIS  in EVOLSTAT
  REAL::     ETE(KHT)    !=TES   in EVOLSTAT
  REAL::     ETI(KHT)    !=TIS   in EVOLSTAT
  REAL::     XXS(KHT)    !=XSI   in EVOLSTAT
  REAL::     XXZ(KHT)    !=ZXSI  in EVOLSTAT
  REAL::     FLUXIN(KIM,KHT)  !=sum(SDZZ(I,.))    in CONTROLPOINT  !TOTAL INPUT IMPURITY FLUX
  REAL::     FLUXOUT(KIM,KHT) !=sum(SDZZ(I,.))    in CONTROLPOINT  !TOTAL OUTPUT IMPURITY FLUX
  REAL::     EDNZ(KIM,KHT)    !=sum(BOUNDZI(L,.)) in EVOLSTAT      !TOTAL IMPURITY Z DENSITY
  REAL::     ECONCZ(KIM,KHT)
  REAL::     XBLADP(KHT) !ND
  REAL::     XBLADZ(KHT) !ND
  REAL::     NGREEN(KHT) !ND
  REAL::     WINT(KHT)   !ND
  REAL::     ECE(KHT)
  REAL::     ETE0(KHT)  
  REAL::     ETI0(KHT)  
  REAL::     ENE0(KHT)  
  REAL::     ENI0(KHT)  
  REAL::     ETEAV(KHT) 
  REAL::     ETIAV(KHT) 
  REAL::     ENEAV(KHT) 
  REAL::     ENIAV(KHT) 
  REAL::     ESHYD(KHT)
  !REAL::     RMIU1(KHT) !ND
  !REAL::     RMIU50(KHT)
  !REAL::     RMIUN(KHT) !ND
  REAL::     FRADC(KHT) !ND
  !FOR SOL-TECXY
  REAL::     XYBLADP      !TODO - HISTORY
  REAL::     XYBLADZ      !TODO - HISTORY
END MODULE

MODULE SPEEDT
  USE PARAMS, ONLY: KHT
  IMPLICIT NONE
  REAL   ::  CT_START  !PROCESSOR TIME START
  REAL   ::  CT_NOW
  REAL::     CT(KHT)   !PROCESSOR TIME LIST FOR EVOLUTION TRACKING
  REAL::     CT_CORE   !PROCESSOR TIME SPENT IN CORE LOOPS
  REAL::     CT_CORE_S
  REAL::     CT_SOL    !PROCESSOR TIME SPENT IN SOL LOOPS
  REAL::     CT_SOL_S
END MODULE SPEEDT

MODULE WYDRUK !ALL BELOW ARE ADDED TOGETHER->SOLRAD IN OUTCORE
  IMPLICIT NONE
  !USED IN OUTSCREEN - ZEROED AND CALUCLATED, THEN OUTCORE:
  REAL::     PLINAD     !=SUM(STLINI(J)*DL    J-IMPURITY INDEX
  REAL::     PLINHE     !=STLINI(LSTTIM(2)))
  REAL::     PSH        !=STLINH*DL+STJONT*DL
  !REAL::     QPLATE
  !REAL::     HYDION
  !REAL::     PLINSP
END MODULE

MODULE CEREC
  IMPLICIT NONE
  REAL::     RCE
  REAL::     RRECYC
END MODULE

MODULE TPEVOL !OK
  USE PARAMS
  IMPLICIT NONE
  INTEGER::  ISTART      !=0    IN INPUTB
  REAL::     RELTT       !=0.2  IN INPUTB
  REAL::     TPLOLD(3,KY)
END MODULE

MODULE CZAS !W SUBRUTYNIE ZERO TIME I WCHAR BYLO ZEROWANE TYLKO DO J=500!   !OK
  USE PARAMS, ONLY: KHB, KHC, KHT !KHT =8000
  IMPLICIT NONE
  !INTEGER::  INDEKS   local in WYDRUKT
  !INTEGER::  IVAR     local in WYDRUKT
  REAL::     WCHAR(KHC,KHT)   !VALUES IN TDEPEND, SOL PROFILES
  REAL::     TIME(KHT)
END MODULE

MODULE PLYTA !OK
  USE PARAMS
  IMPLICIT NONE
  REAL::     FISPUTT           !=0.   IN INIT2
  REAL::     SPUTFLUX(10)      !=0.   IN INIT2  !SIZE=INIM+2
  REAL::     FCSPUT            !=0.2  IN INIT2
  REAL::     YIELH(KX)
  REAL::     YIELZ(KX,KZ)    !NOT DISLPAYED IN DIAGNOSE
END MODULE


! *********************************************** END OF GLOBAL


MODULE TR_MODE !OK
  IMPLICIT NONE
  INTEGER::  I_ANOM
  INTEGER::  I_TURB
  INTEGER::  I_NEO
  REAL::     R_ANOM
  REAL::     R_TURB
  REAL::     R_NEO
  REAL::     ALFAD
  REAL::     ALFAV
  REAL::     RZD_ANOM
  REAL::     RZW_ANOM
  REAL::     GGAMAD     !NOT USED, DIFFERENT NEOTRANSPORT MODEL
  REAL::     GGAMAW     !NOT USED, DIFFERENT NEOTRANSPORT MODEL
END MODULE

MODULE COREDATA !check if optimal
  IMPLICIT NONE
  INTEGER::  NPOINT
  REAL::     RSOL
  REAL::     WN
  REAL::     WTE
  REAL::     WTI
  !REAL::     WNZ  !NEVER USED
  REAL::     WCUR
  REAL::     WPA
  !REAL::     WQ   !NEVER USED
END MODULE

MODULE METRIC
  USE PARAMS
  IMPLICIT NONE
  REAL::     G1(KR)      !=1. IN INIT, =f(...) IN SHAFRANOV, LOCAL VARIABLE IN PROGM & PROGMB, READ FROM IUNIT IN READFILE_NEW
  REAL::     G2(KR)      !=1. IN INIT, =f(...) IN SHAFRANOV, LOCAL VARIABLE IN PROGM & PROGMB, READ FROM IUNIT IN READFILE_NEW
  REAL::     ASURF        !=f(ATOR,GRP,G2) IN INIT, CAN BE CHANGED IN SHAFRANOV
  REAL::     AVOL         !=f(ATOR,A0) IN INIT, CAN BE CHANGED IN SHAFRANOV
  REAL::     A0           !=f(R) IN INIT, CAN BE CHANGED IN SHAFRANOV
  REAL::     ATOR         !=4.*PI**2*GRT IN INIT, CAN BE CHANGED IN SHAFRANOV
  REAL::     WSPC         !READ FROM IPARCORE IN INPUT (MAKING GRID)
END MODULE

MODULE LCMS  !CORE-SOL EXCHANGE MODULE
  USE PARAMS, ONLY: KIM, KZ
  IMPLICIT NONE
  REAL::     DNESOUT   !read from IPARCORE in INPUT (SET VALUE!)
  REAL::     WQTE      !=FLUXTE(LMPC)*EC*ASURF  in TNCHECK
  REAL::     WQTI      !=FLUXTI(LMPC)*EC*ASURF  in TNCHECK
  REAL::     PINPX     !=f(POHM,PADDT,PALFA,PBREM,PLINR,PJON,PSYNCH) in XTAUE
  !USED IN CORE2TECXY FOR STORAGE OF OLD VALUES.
  REAL::     WQTEOLD
  REAL::     WQTIOLD

  !FROM SOL SIDE
  REAL::     TES       !read from iparcore IN input, =f(SUMTE/SUMX,REL,TESO) in SOL2CORE
  REAL::     TIS       !=100. in INPUT,              =f(SUMTI/SUMX,REL,TISO) in SOL2CORE
  REAL::     DNES      !=DNESOUT in INPUT, =GNE(LMPC) in INIT, =f(SUMNE/SUMX,REL,DNESO) in SOL2CORE
  REAL::     DNIS      !=GNI(LMPC) in INIT, =f(SUMNI/SUMX,REL,DNISO) in SOL2CORE
  REAL*8::   BOUNDZI(KZ,KIM)   !=f(CONCZI,GNE,CRNB()) IN INIT, =RNZI(:,:,LMPC) IN INIT, =f(../SUMX,REL,BOUNDZIO) IN SOL2CORE
  REAL*8::   NEUTZ(KIM)
  !USED FOR STORAGE OF "O" DATA IN SOL2CORE AND TECXY2CORE
  REAL::     TESO             !=TES in SOL2CORE
  REAL::     TISO             !=TIS in SOL2CORE
  REAL::     DNESO            !=DNES in SOL2CORE
  REAL::     DNISO            !=DNIS in SOL2CORE
  REAL*8::   BOUNDZIO(KZ,KIM) !=BOUNDZI(.,.) in SOL2CORE
  REAL*8::   NEUTZO(KIM)

  !CALCULATED IN CORE2SOL
  REAL::     PINP         !=WQTE+WQTI  in TNCHECK, =f(PINP,PINPOLD,REL)  in CORE2SOL
  REAL::     SN0     !total plasma flux through LCMS - from CORE side, see DENSITY
  REAL::     WQ           !=2 in INPUTB, =WQTE/WQTI  in CORE2SOL, =f(WQ,REL,WQOLD)  in CORE2SOL
  REAL::     SZ0(KZ,KIM)  !=FLUXNZ(.,.,.) in TNCHECK, =f(SZ0,SZ0OLD,REL)  in CORE2SOL
  !USED ONLY FOR STORAGE OF "OLD" DATA IN CORE2SOL
  REAL::     PINPOLD !=PINP in CORE2SOL, =0.8*PADD in INPUT
  REAL::     SN0OLD  !INIT IN MAIN?,  =SN0 in CORE2SOL
  REAL::     WQOLD   !=WQ in CORE2SOL
  REAL::     SZ0OLD(KZ,KIM)  !=SZ0  in CORE2SOL, =SN0 in INPUT
END MODULE

MODULE STRUM  !FROM SOL (COREDIV)
  USE PARAMS        !KIM=7,KR=301,KZ=88
  IMPLICIT NONE
!FLUXES:
  REAL:: STN  !TOTAL PLASMA FLUX AT CORE BOUNDARY IN SOL (=SN0), INPUT PARAM
  REAL:: STQ  !TOTAL ENERGY FLUX AT CORE BOUNDARY IN SOL (=PINP), INPUT PARAM
!FLUX DENSITIES AT SEPARATRIX (COREDIV SOL INPUT):
  REAL:: SN   !PLASMA FLUX DENSITY (=STN/ASURF - COREDIV)
  REAL:: SQ   !TOTAL ENERGY FLUX DENSITY
  REAL:: SQE  !ELECTRON ENERGY FLUX DENSITY
  REAL:: SQI  !ION ENERGY FLUX DENSITY
  REAL:: STZ(KIM) !TOTAL PARTICLE FLUX FOR EACH IMPURITY
!FLUX DENSITIES AT CORE BOUNDARY (TECXY SOL INPUT)
!  REAL:: SNX  !MAIN PLASMA ION FLUX DENSITY
!  REAL:: SQX  !TOTAL ENERGY FLUX DENSITY
!  REAL:: SEX  !ELECTRON ENERGY FLUX DENSITY
!  REAL:: SIX  !ION ENERGY FLUX DENSITY
END MODULE

MODULE SEPARATRIX  !RACZEJ SOL, NOW USED ALSO IN TECXY
  USE PARAMS
  IMPLICIT NONE
  REAL::     NISEP   !READ FROM IPARSOL IN INPUT (IF KBOUND==0), USED ONLY IN NSEP IN BDNY
  REAL::     TESEP   !READ FROM IPARSOL IN INPUT (IF KBOUND==0), USED ONLY IN BOUNDTY
  REAL::     TISEP   !READ FROM IPARSOL IN INPUT (IF KBOUND==0), USED ONLY IN BOUNDTY
  !REAL::     SEPN    !=NSFLUX(LSTZ,L) IN BDNY  (VERY LOCAL!)
  real::      AREA   !CALCULATED IN MAGCOORD_NEW, BUT OVERWRITTEN FROM CORE
END MODULE

MODULE SOURCE !OK
  USE PARAMS
  IMPLICIT NONE  !ELOSSES
  REAL::     ZEJ(KR)  !ELECTRON ENERGY SOURCE, USED IN TDISC
  REAL::     ZEN(KR)  !=0,                     USED IN TDISC
  REAL::     ZIJ(KR)  !ION ENERGY SOURCE,      USED IN TDISC
  REAL::     ZIN(KR)  !=0,                     USED IN TDISC
END MODULE

MODULE SOURCENI !OK
  USE PARAMS
  IMPLICIT NONE
  REAL::     ZNIJ(KR)  !CALCULATED IN NISOURCE
  REAL::     ZNIN(KR)  !=0             IN NISOURCE
  REAL::     SNI0       !=1E30 IN INPUT
END MODULE

MODULE SOURCENZ !BOTH USED IN NZDISCS
  USE PARAMS
  IMPLICIT NONE
  REAL::     ZNZJ(KZ,KR)  !IMPURITY SOURCE (NON-0 ONLY FOR He)
  REAL::     ZNZN(KZ,KR)  !IMPURITY NEUTRALS SOURCE?
END MODULE

MODULE SOURHE !OK
  USE PARAMS
  IMPLICIT NONE
  REAL::     SHE(KR)  !=0 in INIT, used in NISOURCE, NZSOURCE
  REAL::     SHYD(KR) !=0 in INIT,=SNI0*EXP(-WYKL) in NISOURCE - SOURCE OF HYDROGEN
  REAL::     SNDD(KR) !=...  in  ELOSSES, D-D NEUTRON SOURCE
  REAL::     XLAMBDA   !=f(VTI,HYDIONL,GNE)  in NISOURCE, used in calculating WYKL
END MODULE

MODULE CORE
  USE PARAMS
  IMPLICIT NONE
  INTEGER::  LMPC       !READ FROM IPARCORE IN INPUT
  REAL::     GNE(KR)
  REAL::     DGNE(KR)
  REAL::     GNI(KR)
  REAL::     DGNI(KR)
  REAL::     GTE(KR)   !BEFORE TE
  REAL::     GTI(KR)   !BEFORE TI
  REAL::     R(KR)
  REAL::     RSTEP(KR)   !=R(M+1)-R(M) IN GRID
  REAL::     RMID(KR)
  REAL::     Z(KR)
  REAL::     GZEFF(KR) !BEFORE ZEFF
  REAL::     GCUR(KR)  !BEFORE CUR
  REAL::     GQ(KR)    !BEFORE Q
  REAL::     BP(KR)
  REAL::     GHE(KR)
  REAL::     PROM(KR)  !
  REAL::     GNTOT(KR)
  REAL::     GZTOT(KR) !NOT VERY OFTEN USED
  REAL::     GPEE(KR)
  REAL::     GPII(KR)
  REAL::     PRESS(KR) !CALC. IN TEITI
  REAL::     PRESST(KR) !CALC IN OUTPUT, DIFFERENT UNIT, INCLUDES IMPURITIES
END MODULE

MODULE IMPCORE
  USE PARAMS    !KIM=7,KR=301,KZ=88
  IMPLICIT NONE
  REAL*8::     RNZI(KZ,KR,KIM) !NA STPONIE JONIZACJI
  REAL*8::     RN0I(KR,KIM)
  REAL*8::     RNZ(KZ,KR)
  REAL*8::     RN0(KR)
  !REAL*8::     BOUNDZI(KZ,KIM)   !=f(CONCZI,GNE,CRNB()) IN INIT, =RNZI(:,:,LMPC) IN INIT, =f() IN SOL2CORE
  REAL*8::     ZEFFA             !=f(GZEFF,R) IN OUTCORE, LOCAL VARIABLE IN OUT1
  REAL::       CONCZI(KIM)        !READ FROM IPARCORE IN INPUT
END MODULE

MODULE LOSSES   !CALCULATED MOSTLY IN ELOSSES
  USE PARAMS
  IMPLICIT NONE
  REAL::     QTOT(KR)
  REAL::     PAUX(KR)
  REAL::     PQALPHA(KR)
  REAL::     PQOHM(KR)
  REAL::     QBREM(KR)
  REAL::     QSYNCH(KR)
  REAL::     QLINTOT(KR)       !BEFORE PQLIN
  REAL::     QJON(KR)

  REAL::     QH(KR)
  !SHYD
  !SHE
  !SNDD
  REAL::     QJONI(KR,KIM)     !PROFILE FOR EACH IMPURITY
  REAL::     PQLINI(KR,KIM)    !PROFILE FOR EACH IMPURITY

  REAL::     QREC(KR)
  !REAL::     PQLIN(KIM,KZ,KR)  !BEFORE QLIN
  REAL::     PQLIN(KZ,KR,KIM)   !PROFILE FOR IONIZATION STAGE OF EACH IMPURITY



END MODULE

MODULE TOTALS
  USE PARAMS, ONLY: KIM
  REAL::     PTOT
  REAL::     PADDT
  REAL::     PALFA
  REAL::     POHM
  REAL::     PBREM
  REAL::     PSYNCH
  REAL::     PLIN
  REAL::     PJON

  REAL::     PQH
  REAL::     SHYDT
  REAL::     SHET
  REAL::     SOUDD
  REAL::     PLOSSI(KIM) !average of the sum QJONI+PQLINI
  REAL::     PINPUT  !=PTOT-PBREM-PLIN-PJON-PQH-PSYNCH
  REAL::     SOLRAD  !=PLINAD+PLINSP+PLINHE+PSH !from SOL
  REAL::     PCORELOSS
  REAL::     PTOTLOSS
END MODULE TOTALS


MODULE FLUXES !CORE
  USE PARAMS    !KIM=7,KR=301,KZ=88,KH3=1001,KH4=10
  IMPLICIT NONE
  REAL::     FLUXNE(KR)        !=FLUXNE+K*FLUXNZ()  IN DENSITY
  REAL::     FLUXNI(KR)        !USED IN TNCHECK - SN0
  REAL::     FLUXNZ(KZ,KR,KIM) !USED IN TNCHECK - SZ0
  REAL::     FLUXTE(KR)        !USED IN TNCHECK - WQTE
  REAL::     FLUXTI(KR)        !USED IN TNCHECK - WQTI
  REAL::     FLUXION(KR)       !=FLUXNI+FLUXNZ()    IN DENSITY
  REAL::     FLUXNEO(KR)       !never initialized!
END MODULE

MODULE RITMTR !NEEDS ALFAD, ALFAV
  USE PARAMS
  IMPLICIT NONE
  REAL::     DDITG(KR)    ! 4DP 4CP
  REAL::     DDDTE(KR)    ! 4DP 4CP, =0 if R_TURB==0, USED IN TCOEF
  REAL::     DDDRB(KR)    ! 4DP 4CP
  REAL::     DDDA(KR)     ! 4DP 4CP
  REAL::     DCORE(KR)    ! 4DP 4CP
  REAL::     VVITG(KR)    ! 4VP
  REAL::     VVDTE(KR)    ! 4VP
  REAL::     DPERMI(KR)   !          =0 if R_TURB==0, USED IN COEFNI (*R_TURB)
  REAL::     CPERMI(KR)   !          =0 if R_TURB==0
  REAL::     VPERMI(KR)   !          =0 if R_TURB==0, USED IN COEFNI
END MODULE

MODULE TCOEFFG
  USE PARAMS, ONLY: KR
  IMPLICIT NONE
  REAL::     DDIFNE(KR)      !FROM COEFFNE
  REAL::     WDIFNE(KR)      !   --//--
  REAL::     DDIFNI(KR)      !FROM COEFFNI
  REAL::     WDIFNI(KR)      !   --//--
  REAL::     XEE(KR)         !FROM COEFFTG
  REAL::     XII(KR)         !   --//--
  REAL::     VTE(KR)         !   --//--
  REAL::     VTI(KR)         !   --//--
  REAL::     VPINCH(KR)      !   --//--
  REAL::     FSH(KR)         !FROM TR_SHAPE
  REAL::     FUNR(KR)        !   --//--
  REAL::     CDCE(KR)        !FROM COEFFT
  REAL::     CDCI(KR)        !   --//--
  REAL::     CVCE(KR)        !   --//--
  REAL::     CVCI(KR)        !   --//--
  !TRANSPORT BARRIER PARMETERS
  REAL::     BAR_A
  REAL::     BAR_EX
  REAL::     BAR_X0
  !TRANSPORT COEFFICIENT FUNCTION SHAPE PARAMETERS
  REAL::     TFPA
  REAL::     TFPEX
  !SFUNR SHAPE PARAMETERS
  REAL::     SFR_X0
  REAL::     SFR_DELTA
  !OTHER
  REAL::     CV

END MODULE

MODULE COEFFNZ !OK
  USE PARAMS    !KIM=7,KR=301,KZ=88
  IMPLICIT NONE
  REAL::     DDIFNZ(KIM,KZ,KR)
  REAL::     WDIFNZ(KIM,KZ,KR)
END MODULE

MODULE COEFFNEO !OK
  USE PARAMS
  IMPLICIT NONE
  REAL::     DDIFNEONI(KR)          !NOT USED YET
  REAL::     WDIFNEONI(KR)          !NOT USED YET
  REAL::     DDIFNEONZ(KIM,KZ,KR)       ! IN NEOCLASSICS
  REAL::     WDIFNEONZ(KIM,KZ,KR)       ! IN NEOCLASSICS
  REAL::     CDCNEOE(KR)            !NOT USED YET
  REAL::     CDCNEOI(KR)                ! IN NEOCLASSICS
  REAL::     CVCNEOE(KR)            !NOT USED YET
  REAL::     CVCNEOI(KR)            !NOT USED YET
END MODULE

MODULE COLLIS
  IMPLICIT NONE
  REAL::     RMIU1
  REAL::     RMIU50
  REAL::     RMIUN
END MODULE

MODULE EFOLD !CORE
  USE PARAMS
  IMPLICIT NONE
  REAL::     EFTI(KR)
  REAL::     EFTE(KR)
  REAL::     EFNE(KR)
  REAL::     EFNI(KR)
  REAL::     EFQSF(KR)
  REAL::     EFPTOT(KR)
END MODULE

MODULE ITEROLD
  USE PARAMS
  IMPLICIT NONE
  REAL::     GNIOLD(KR)
  REAL::     GNEOLD(KR)
  REAL::     GTEOLD(KR)
  REAL::     GTIOLD(KR)
  REAL::     RNZIOLD(KZ,KR,KIM)
  REAL::     RN0IOLD(KR,KIM)
  REAL::     REL                 !READ FROM IPARCORE IN INPUT
  REAL::     RELN                !=0.1  in TIME_STEPS (nonlinear iterations, regulated internally)
  REAL::     RELD                !=REL  in DENSITY
  REAL::     RELZ                !=REL  in SOLVE_IMPUR, BUT THEN =1.
  REAL::     RELC                !=REL  in CORE2SOL
  REAL::     RELS                !=REL  in SOL2CORE
  REAL::     RELT                !=REL  in TEITI
  REAL::     CE                  !READ FROM IPARCORE IN INPUT
  REAL::     CI                  !=CE                IN INPUT
  REAL::     RELL                !IN XYCOEFF, TECXY
  REAL::     RELM                !IN XYCOEFF, TECXY
  real::     RELTNP              !FROM TECXY
END MODULE

MODULE TEMPOLD
  USE PARAMS
  IMPLICIT NONE
  REAL::     GNIOT(KR)
  REAL::     GNEOT(KR)
  REAL::     GTEOT(KR)
  REAL::     GTIOT(KR)
  REAL::     GNTOTOT(KR)
  REAL::     RNZIOT(KZ,KR,KIM)
  REAL::     RN0IOT(KR,KIM) !!
  REAL::     RNZOT(KZ,KR)
  REAL::     RN0OT(KR)
END MODULE

MODULE EFOLD_OLD
  USE PARAMS
  IMPLICIT NONE
  REAL::     EFTIO(KR)
  REAL::     EFTEO(KR)
  REAL::     EFNEO(KR)
  REAL::     EFNIO(KR)
  REAL::     EFQSFO(KR)
  REAL::     EFPTOTO(KR)
  REAL::     AFOLD
END MODULE

MODULE ENERGIA  !OK
  IMPLICIT NONE
  REAL::     TAUE
  REAL::     TAUER
  REAL::     TAUEEX !=WINT/PINPX  in XTAUE
  !REAL::     WINT
  REAL::     PRATIO
  REAL::     PRATIO2
  REAL::     PTH    !POWER TRESHOLD
END MODULE

MODULE ACOEF
  USE PARAMS  !KIM=7,KR=301,KZ=88
  IMPLICIT NONE
  REAL*8::     ALFAI(KZ,KR,KIM)  !SLIGHTLY FASTER
  REAL*8::     BETAI(KZ,KR,KIM)  !SLIGHTLY FASTER
END MODULE

MODULE IMPURITY1
  USE PARAMS
  IMPLICIT NONE
  REAL:: ALFF(KHB,KIM,KZ)  !FASTER
  REAL:: BETT(KHB,KIM,KZ)  !FASTER
  REAL:: GAMM(KHB,KIM,KZ)  !FASTER - NOT USED
  REAL:: SLIN(KHB,KIM,KZ)
  REAL:: POTJON(KZ,KIM)
END MODULE


! *********************************************** END OF CORE


!MODULE OPTSOL
!  IMPLICIT NONE
!  !LOGICAL::   IOPNE    !=1/=0 IN INPUTB (READ INPUTSOL? - INIT1B - MAIN PLASMA)
!  !LOGICAL::   IOPNZ    !=1/=0 IN INPUTB (READ INPUTSOL? - INIT2  - IMPURITIES)
!END MODULE OPTSOL

MODULE INITVARS
  IMPLICIT NONE
  REAL:: SNE0
  REAL:: SNEK
  REAL:: STI0
  REAL:: STE0
  REAL:: STIK
  REAL:: STEK
  REAL:: SN0K
END MODULE INITVARS

MODULE NET !OK
  USE PARAMS
  IMPLICIT NONE
  INTEGER::  IMX           !READ FROM IPARSOL IN INPUTB
  INTEGER::  IMY           !READ FROM IPARSOL IN INPUTB
  REAL::     X(KX1)       !=f()   IN SIATKA
  REAL::     Y(KY1)       !=f()   IN SIATKA
  REAL::     XP            !=0           IN INPUTB
  REAL::     XS            !=f(RP,ELONG,ILZER) IN INPUTB
  REAL::     XK            !=1.2*XS      IN INPUTB
  REAL::     YP            !READ FROM IPARSOL IN INPUTB
  REAL::     YK            !READ FROM IPARSOL IN INPUTB
  REAL::     SEFF          !=f()         IN MAGCOORD,  NOT USED
  REAL::     SOLWD         !=YK-YP       IN INPUTB
  REAL::     DL            !=AREAL/WXS   IN INPUTB   !MOVE TO SEPARATRIX
  REAL::     WX        !READ FROM IPARSOL IN INPUTB
  REAL::     WY        !READ FROM IPARSOL IN INPUTB
  REAL::     XSF       !LEG LENGTH FACTOR: XK=XSF*XS
  real::     YTRANS
  integer::  JLINE
  integer::  JVEND
!TO BE DONE IN THE FUTURE:
  !REAL::     XX(KX1)      !=f()   IN SIATKA
  !REAL::     HX(KX1)      !=f()   IN SIATKA
  !REAL::     YY(KX1)      !=f()   IN SIATKA
  !REAL::     HY(KX1)      !=f()   IN SIATKA
  !REAL::     DXX(SNS) !DXX=X(I+1)-X(I), I=2,IMX DEFINED IN BRZEG
END MODULE

MODULE GEOMETRY !OK
  USE PARAMS
  IMPLICIT NONE
  REAL::     RX(KX,KY)      !=1. IN MAGCOORD
  REAL::     RY(KX,KY)      !=1. IN MAGCOORD
  REAL::     GG(KX,KY)      !=1. IN MAGCOORD
  REAL::     BRATIO(KX,KY)  !=BP00/BT FROM RADIAL IN MAGCOORD
  real::      BTOR(KX,KY)   !FROM TECXY
  real::      BTOT(KX,KY)   !FROM TECXY
  real::      RZ(KX,KY)     !FROM TECXY
END MODULE

MODULE PLASMA
  USE PARAMS
  IMPLICIT NONE
  REAL::     XSI             !=0.   IN INPUTB, =(FDIV+FWALL+FBACK)/(FINPUT+SVOL) IN RECYCH,    "FOUT/FI0  DLA WODORU"
  !REAL::     RECYC     !READ FROM IPARSOL IN INPUTB
  real::     RECYCR  !OUTER
  real::     RECYCL  !INNER
  REAL::     NE(KX,KY)
  REAL::     NI(KX,KY)
  REAL::     TE(KX,KY)
  REAL::     TI(KX,KY)
  REAL::     VI(KX,KY)
  REAL::     UI(KX,KY)
  !REAL::     V0(KX,KY,IG)  !WHY IG=5?
  !REAL::     U0(KX,KY,IG)  !WHY IG=5?
  REAL::     ZEFF(KX,KY)
  !REAL::     V0PAR(KX,KY)  !NEVER USED IN COREDIV
  REAL::     VIPAR(KX,KY)
  REAL::     VEPAR(KX,KY)
  REAL::     ELF(KX,KY)
  REAL::     VE(KX,KY)
  REAL::     UE(KX,KY)
  REAL::     CURX(KX,KY)
  REAL::     CURY(KX,KY)
  !REAL::     T0(KX,KY,IG)  !WHY IG=5?
  !REAL::     N0(KX,KY,IG)  !WHY IG=5?
  !REAL::     TZ0(KX,KY)   !moved to IMPUR
  REAL::     ETAIX(KX,KY)
  REAL::     ETAIY(KX,KY)
  real::     NITOT(KX,KY)  !TECXY ONLY
END MODULE

MODULE NEUTRALS
  USE PARAMS
  IMPLICIT NONE
  integer::  IGRUP            !FROM TECXY
  integer::  IMODEL           !FROM TECXY
  REAL::     N0(KX,KY,IG)
  REAL::     T0(KX,KY,IG)
  REAL::     V0(KX,KY,IG)
  REAL::     U0(KX,KY,IG)
  real::     V0PAR(KX,KY,IG)  !FROM TECXY
  real::     V0PERP(KX,KY,IG) !FROM TECXY
  real::     U0X(KX,KY,IG)    !FROM TECXY
  !TO BE UNIFIED AFTER CHANGES IN COREDIV MODEL WITH IMPUR/IMPURALL
  real::     TZ0(KX,KY,KIM)   !FROM TECXY
END MODULE

MODULE IMPUR !OK
  USE PARAMS
  IMPLICIT NONE
  !REAL::     AMZ
  REAL::     ZM              !MASA JONU DOMIESZKI (KG)
  REAL::     ZXSI            !=0.   IN INPUTB    "FOUT/FI0  DLA DOMIESZEK  ZXSI"
  REAL::     NZ(KX,KY,KZ)
  REAL::     VZ(KX,KY,KZ)
  REAL::     VZPAR(KX,KY,KZ)
  REAL::     UZ(KX,KY,KZ)
  REAL::     TZ0(KX,KY)
  REAL::     ETAZX(KX,KY,KZ)  !NOT DISPLAYED IN DIAGNOSE
  REAL::     ETAZY(KX,KY,KZ)  !NOT DISPLAYED IN DIAGNOSE
  REAL::     SOUZ0(KX,KY,KZ)  !=f(...) IN RSIDEN, =0. IN ZERO
  REAL::     SOUZ1(KX,KY,KZ)  !=f(...) IN SOURVE, =0. IN ZERO
  REAL::     SDZ(KZ)        !=SDZZ(INIMI,:) IN GETIMP, =SRN IN INITIATE_SOL (STRUMIEN)
END MODULE

MODULE IMPURALL !OK
  USE PARAMS
  IMPLICIT NONE
  !REAL::     CONCZ(KIM)   !READ FROM IPARSOL IN INPUTB, THEN *0.01
  REAL::     ZXSII(KIM)
  REAL::     NZZ(KIM,KX,KY,KZ)
  REAL::     VZZ(KIM,KX,KY,KZ)
  REAL::     UZZ(KIM,KX,KY,KZ)
  REAL::     TZZ0(KIM,KX,KY)
  REAL::     VZZPAR(KIM,KX,KY,KZ)
  REAL::     ETAZXX(KIM,KX,KY,KZ)
  REAL::     ETAZYY(KIM,KX,KY,KZ)
  REAL::     SOUZZ0(KIM,KX,KY,KZ)
  REAL::     SOUZZ1(KIM,KX,KY,KZ)
  REAL::     SDZZ(KZ,KIM)   !=FLUXNZ(:,:,LMPC) IN CORE2SOL (STRUMIEN)
  REAL::     SDZZOLD(KZ,KIM)  !INIT IN MAIN?
END MODULE

module IMPUR_mod
  !use grid_param
  USE PARAMS
  implicit none
  real::      NZ(KX,KY,KZ,KIM)
  real::      VZ(KX,KY,KZ,KIM)
  real::      UZ(KX,KY,KZ,KIM)
  real::      DNZS(KZ,KIM)     !FLUX DENSITY FROM CORE
  real::      SOUZ0(KX,KY,KZ,KIM)
  real::      SOUZ1(KX,KY,KZ,KIM)
  real::      VZPAR(KX,KY,KZ,KIM)
end module

MODULE ZRODLA !OK
  USE PARAMS
  IMPLICIT NONE
  REAL::     SOU0(KX,KY)          !=f(...) IN RSIDEN, =0. IN ZERO
  REAL::     SOU1(KX,KY)          !=f(...) IN SOURVE, =0. IN ZERO
  real::     SOUTE(KX,KY)
  real::     SOUTI(KX,KY)
END MODULE

MODULE FLUX
  USE PARAMS
  IMPLICIT NONE
  REAL::     FLUXX(KX,KY,KZ)
  REAL::     FLUXY(KX,KY,KZ)
  REAL::     FLUXV(KX,KY,KZ)
END MODULE

MODULE LIGHT !OK
  USE PARAMS
  IMPLICIT NONE
  REAL::     QLIN(KX,KY,KZ)  !NOT DISPLAYED IN DIAGNOSE
  REAL::     QLINI(KIM,KX,KY,KZ)
END MODULE

MODULE EQUILIB
  USE PARAMS, ONLY: KX, KZ
  IMPLICIT NONE
  REAL::     RCRN(KX,KZ)  !WAS: RCRN(100,88)
END MODULE

MODULE PRES !OK
  USE PARAMS
  IMPLICIT NONE
  REAL::     PII(KX,KY)
  REAL::     PEE(KX,KY)
END MODULE

MODULE SOLY
  USE PARAMS
  IMPLICIT NONE
  REAL::     HLINY(KY)
  REAL::     PLINY(KIM,KY)
  REAL::     SHJONY(KY)
  REAL::     SJONY(KIM,KY)
  REAL::     HLINX(KX)
  REAL::     PLINX(KIM,KX)
  REAL::     SHJONX(KX)
  REAL::     SJONX(KIM,KX)
  REAL::     DENIMPX(KIM,KX)
  REAL::     CONCX(KIM,KX)
  REAL::     CONCD(KIM)
END MODULE

MODULE CONDC !OK
  USE PARAMS
  IMPLICIT NONE
  REAL::     HIPRE(KX,KY)
  REAL::     HIPARE(KX,KY)
  REAL::     HIPRI(KX,KY)
  REAL::     HIPARI(KX,KY)
END MODULE

MODULE RADIAL
  USE PARAMS
  IMPLICIT NONE
  REAL::     DIFH     !=0.5       IN INPUTB
  REAL::     DIFA     !=DIFH      IN INPUTB
  REAL::     DIFE     !=DIFH      IN INPUTB
  REAL::     VINW     !=0.        IN INPUTB
  REAL::     VINH     !=0.        IN INPUTB
  REAL::     GAMAD    !=0.        IN INPUTB
  REAL::     GAMAW    !=0.        IN INPUTB
  REAL::     ETAY0    !=0.33*DIFH IN INPUTB
  REAL::     CONDE    !=2.*DIFH   IN INPUTB
  REAL::     CONDI    !=1.*DIFH   IN INPUTB
END MODULE

MODULE BCRAD !RADIAL BAOUNDARY CONDITIONS MODULE
  USE PARAMS
  IMPLICIT NONE
  REAL::     YLAMN   !=0.03       IN INPUTB  !FOR TOKAMAK WALL
  REAL::     YLAMTE  !=0.04       IN INPUTB  !..
  REAL::     YLAMTI  !=0.03       IN INPUTB  !..
  REAL::     YLAMNP   !=1.E10      IN INPUTB  !FOR PR (ONLY COREDIV)
  REAL::     YLAMTEP  !=1.E10      IN INPUTB  !./
  REAL::     YLAMTIP  !=1.E10      IN INPUTB  !..
  real::      DNSEPI  !MOVED FROM TECXY, MAY BE OBSOLETE
  real::      DNSEPZ  !MOVED FROM TECXY, MAY BE OBSOLETE
END MODULE

MODULE ATIME  !OK
  USE PARAMS
  IMPLICIT NONE
  REAL::     TAUII(KX,KY)
  REAL::     TAUEE(KX,KY)
END MODULE

MODULE CORET !TRANSPORT COEFF. AT SEPARATRIX, ALL VALUES IN CORE2SOL
  IMPLICIT NONE
  REAL::     CDIFA    !=DDIFNI(LMPC)         //COEFFNI
  REAL::     CVINW    !=VTE(LMPC)            //COEFFTG
  REAL::     CDIFH    !=DDIFNI(LMPC)         //COEFFNI
  REAL::     CVINH    !=VTE(LMPC)            //COEFFTG
  REAL::     CETAY0   !=1./3.*DDIFNI(LMPC)   //COEFFNI
  REAL::     CCONDE   !=XEE(LMPC)            //COEFFTG
  REAL::     CCONDI   !=XII(LMPC)            //COEFFTG
  REAL::     CDIFE    !=DDIFNI(LMPC)         //COEFFNI
  REAL::     BARWD
END MODULE

MODULE DPROF !OK
  USE PARAMS
  IMPLICIT NONE
  REAL::     DDPROF(KX,KY)
  REAL::     DDPROFZ(KX,KY)
  REAL::     CHIPROFE(KX,KY)
  REAL::     CHIPROFI(KX,KY)
  REAL::     VPPROF(KX,KY)
END MODULE

MODULE PLYTA1 !OK
  USE PARAMS
  IMPLICIT NONE
  REAL::     QPE
  REAL::     QPI
  REAL::     STLIN
  REAL::     STLINH
  REAL::     FISPUTDL
  REAL::     STJONT
  REAL::     PBREMSOL
END MODULE

MODULE PLATE !OK
  USE PARAMS
  IMPLICIT NONE
  REAL::     YSHAPE(100)
  REAL::     FFAST
  REAL::     FSLOW          !=1.0-FFAST IN INPUTB
  !REAL::     FIDOD         !NOT USED BESIDE INITIALIZATION
END MODULE

MODULE DIVSURFACE !USED IN SOL: RECYCZ, VAPORIZATION, 
                  !    EFLUXTODIV, OUTSOL, RPROFILES
  USE PARAMS
  IMPLICIT NONE
  REAL::     TDSMAX
  REAL::     TDSMIN
  REAL::     TSURF(2,KY1)  !ACHTUNG! KY=KY OTHERWISE SOL &TECXY NOT COMPATIBLE
                            !IN COREDIV SOL ONLY INDEX 1 IS USED
  REAL::     EFLMAX
  REAL::     VF
  REAL::     VAPFLUX(KY1)     !SNS=KY1
  REAL::     P2DIVLOC(KY1)    !SNS=KY1
  REAL::     P2DIVPAR(KY1)    !SNS=KY1
  REAL::     DANGLE
END MODULE

module BTX  !from TECXY, ONLY INDEX 2 IS USED IN COREDIV
  use PARAMS
  implicit none
  real::      PRMI(2,KY)
  real::      PRMZ(2,KY,KZ,KIM)
  real::      PFE(2,KY)
  real::      PFI(2,KY)
  real::      PFZ(2,KY,KZ,KIM)
end module

MODULE KINET !OK
  USE PARAMS, ONLY: BFS
  IMPLICIT NONE
  REAL::     FFE(BFS)
  REAL::     FFI(BFS)
  REAL::     FFZ(BFS)
  REAL::     RMI(BFS)
  REAL::     RMZ(BFS)
END MODULE

MODULE BOUND
  USE PARAMS
  IMPLICIT NONE
  REAL::     A1(2,2)
  REAL::     B1(2)
  REAL::     A2(2,2)
  REAL::     B2(2)
END MODULE

MODULE GRANICE
  IMPLICIT NONE
  REAL::     YY1
  REAL::     YY2
END MODULE

MODULE WODOR
  USE PARAMS, ONLY: KHB
  IMPLICIT NONE
  REAL::     ALFFH(KHB)
  REAL::     BETTH(KHB)
  REAL::     GAMMH(KHB)
END MODULE

MODULE IMPURITY
  USE PARAMS, ONLY: KIM, KHB, KZ    !7, 500, 88
  IMPLICIT NONE
  REAL::     ALFF(KHB,KZ,KIM)
  REAL::     BETT(KHB,KZ,KIM)
  REAL::     GAMM(KHB,KZ,KIM)
  REAL::     PLIN(KHB,KZ,KIM)  !MOVED FROM RADIAT
  REAL::     POTJON(KZ,KIM)    !MOVED FROM POT
END MODULE

MODULE ATOM
  USE PARAMS
  IMPLICIT NONE
  REAL::     ALFA(KZ,KX,KY)
  REAL::     BETA(KZ,KX,KY)
  REAL::     GAMA(KZ,KX,KY)
  REAL::     ALFH0(IG,KX,KY) !FASTER DATA ACCESS
  REAL::     BETAH(KX,KY)    !OK
  REAL::     GAMAH(IG,KX,KY) !FASTER DATA ACCESS
END MODULE

MODULE ATOMALL
  USE PARAMS   !KIM=7,KZ=88, KX=51, KY=41
  IMPLICIT NONE
  REAL::     ALFAG(KZ,KIM,KX,KY)   !ALFAG(L,INIMI,I,J)
  REAL::     BETAG(KZ,KIM,KX,KY)
  REAL::     GAMAG(KZ,KIM,KX,KY)
END MODULE


! *********************************************** END OF SOL
! ********************************* TECXY MODULES BEGIN HERE


      module PARAM_mod
      !use grid_param
      implicit none
      !integer::   LST
      !real::      WX
      !real::      WY
      !real::      HT
      !real::      RMACH
      !real::      RECYCR  !PROBABLY OUTER
      !real::      RECYCL  !PROBABLY INNER
      !real::      ZRECYC
      !integer::   IMAP
      !real::      SNZ
      real::      SN      !  PLASMA        FLUX DENITY FROM THE CORE
      real::      SQE     !ELECTRON ENERGY FLUX DENITY FROM THE CORE
      real::      SQI     !     ION ENERGY FLUX DENITY FROM THE CORE
      !real::      FE(KX)  !NEVER USED
      !real::      FI(KX)  !NEVER USED
      !real::      FE0
      !real::      FI0
      !real::      FLIME
      !real::      FLIMI
      !real::      WKR
      !integer::   LNST
      !integer::   IGRUP
	  !REAL*8 ::   PROGFACT   !MOVED FROM WARIANT2_MOD
      end module


      module DRIFT_mod
      !use grid_param
	  USE PARAMS
      implicit none
      integer::   IDRYF
      real::      PHIP(KX,KY)
      real::      CURPAR(KX,KY)
      real::      CURDIAM(KX,KY)
      real::      VDIAMI(KX,KY)
      real::      VDIAME(KX,KY)
      real::      VDIAMZ(KX,KY,KZ,KIM)
      real::      VRADI(KX,KY)
      real::      VRADE(KX,KY)
      real::      VRADZ(KX,KY,KZ,KIM)
      real::      PSI1(KX,KY)
      real::      PSI2(KX,KY)
      real::      PSITOT(KX,KY)
      real::      BFUN(KX,KY)
      real::      SPSI1(KX,KY)
      real::      SPSI2(KX,KY)
      real::      BFUNZ(KX,KY,KZ,KIM)
      real::      SIGMA(KX,KY)
      real::      ALPX
      real::      ALPY
      real::      PHISR(KY)
      real::      PHISL(KY)
      real::      PHISRA(KY)
      real::      PHISLA(KY)
      real::      OMSTAR(KX,KY)
      real::      OMSTARZ(KX,KY,KZ,KIM)
      end module

      module CURITER_mod
      !use grid_param
	  USE PARAMS
      implicit none
      real::      REL00
      real::      REST(KY,2)
      real::      RFUN(KY,2)
      real::      XNORM(KY)
      real::      PHIOLD(KX,KY)
      real::      CURPARO(KX,KY)
      real::      CURDIAO(KX,KY)
      real::      VDIAMIO(KX,KY)
      real::      VDIAMEO(KX,KY)
      real::      VDIAMZO(KX,KY,KZ,KIM)
      real::      VRADIO(KX,KY)
      real::      VRADEO(KX,KY)
      real::      VRADZO(KX,KY,KZ,KIM)
      real::      CURXO(KX,KY)
      real::      CURYO(KX,KY)
      real::      VIO(KX,KY)
      real::      VEO(KX,KY)
      real::      VZO(KX,KY,KZ,KIM)
      real::      OMSO(KX,KY)
      real::      OMSZO(KX,KY,KZ,KIM)
      real::      RADD(KY,2)
      integer::   ILOOP
      integer::   IDSTART
      integer::   IDLIN
      integer::   IL
      integer::   IDUMP
      integer::   IDIST
      real::      REL
      end module

      module LFS_mod
      !use grid_param
      implicit none
      integer::   ILOSSES
      real::      NEONSET
      real::      TEONSET
      end module

      module IMPPAR_mod
      !use grid_param
	  USE PARAMS
      implicit none
      !integer::   INIM
      !integer::   LSTT(KIM)
      !integer::   LSTNN(KIM)
      !real::      ZMM(KIM)
      !real::      AMZZ(KIM)
      !integer::   IMTYPE(KIM)
      !real::      CONCZ(KIM)
      real::      CONCZ_SOL(KIM)
	  real::      CONCZ_PRI(KIM)
	  real::      CONCZ_PRO(KIM)
	  REAL::      CONCZ_SEP(KIM)
      !real::      ZRECYCC(KIM)
      end module

      module OUT_mod
      !use grid_param
	  USE PARAMS
      implicit none
      real::      XSI     !in XYDNEUTRAL  (FINPUT-FLIMH)/(FLIM+FWALLH+FWALL)
      real::      XSIH    !in XYDNEUTRAL  -(FWALLH+FLCMS+SVOLH)/FLIMH
      real::      ZXSI(KIM) !in XYRECYCZ  (SVOL+FINPUTR+FINPUTL)/(FLIMR+FLIML+FBACK+FWALL)
      real::      SDOD(KX,KY,KZ,KIM)
      real::      YIELH(KX)
      real::      YIELZ(KX,KZ,KIM)
      end module

      module MESH_mod
      use PARAMS
      implicit none
      real::      HNX(KX)
      real::      HVX(KX)
      real::      HNY(KY)
      real::      HVY(KY)
      real::      XN(KX)  !X COORDINATES IN SOL
      real::      XV(KX)
      real::      YN(KY)
      real::      YV(KY)
      real::      XXS1    ! wsp. X X-point1
      real::      XXS2    ! wsp. X X-point2
      end module

      module TECXY2RITM_mod  !NEVER USED
      !use grid_param
	  USE PARAMS
      implicit none
      real::      DNZS(KZ,KIM)
      real::      NES
      real::      NIS
      real::      TES
      real::      TIS
      end module

      module CZAS_mod
      use PARAMS
      implicit none
      real::      WCHAR(KT1,KT2)
      real::      TIME(KT2)
      integer::   INDEKS
      integer::   IVAR
      end module

      module PLATE_mod
      use PARAMS
      implicit none
      real::      YSHAPE(2,KY)
      !real::      FFAST   !DUPLICATED IN PLATE
      !real::      FSLOW   !DUPLICATED IN PLATE
      real::      FIDOD
      real::      ST0H
      end module

      module LAYERS_mod  !ACHTUNG! CORE PARAMETERS(?)
      use PARAMS
      implicit none
      real::      N0CORE(KX)
      real::      N0ION(KX)
      real::      AFLUX(KX)
      end module

      module NEUTDYF_mod
      use PARAMS
      implicit none
      real::      DYFC(2,KX,KY)
      end module

      module MARFE_mod
      !use grid_param
      implicit none
      integer::   IMARFH
      integer::   IDD
      integer::   IGG
      integer::   JMM
      real::      XD
      real::      XG
      real::      YM
      real::      GAM0
      real::      XGAM
      real::      XGAM0
      real::      TSINK
      end module

      module MARFEZ_mod
      !use grid_param
      implicit none
      integer::   IMARFZ
      real::      GAMZ0
      real::      XGAMZ
      real::      XGAMZ0
      real::      TSINKZ
      end module

      module BUMPER_mod
      !use grid_param
      implicit none
      real::      TBACKH
      real::      TBACKZ
      real::      TADD
      end module

      module CMARFE_mod
      !use grid_param
      implicit none
      integer::   IMC
      integer::   IMCM
      integer::   JMC
      real::      XMC
      real::      XMCM
      real::      YMC
      integer::   IMCZ
      real::      XMCZ
      end module

      module M_PLASMA_mod
      !use grid_param
	  USE PARAMS
      implicit none
      real::      NEV(KX,KY)
      real::      NIV(KX,KY)
      real::      TEV(KX,KY)
      real::      TIV(KX,KY)
      real::      VIN(KX,KY)
      real::      UIN(KX,KY)
      real::      V0N(KX,KY,IG)
      real::      U0N(KX,KY,IG)
      real::      ZEFFV(KX,KY)
      real::      ELFN(KX,KY)
      real::      VEN(KX,KY)
      real::      UEN(KX,KY)
      real::      CURXN(KX,KY)
      real::      CURYN(KX,KY)
      real::      T0V(KX,KY,IG)
      real::      N0V(KX,KY,IG)
      real::      TZ0V(KX,KY,KIM)
      end module

      module M_IMPUR_mod
      !use grid_param
	  USE PARAMS
      implicit none
      real::      NZV(KX,KY,KZ,KIM)
      real::      VZN(KX,KY,KZ,KIM)
      real::      UZN(KX,KY,KZ,KIM)
      end module

      module M_CONDC_mod
      use PARAMS
      implicit none
      real::      HIPREV(KX,KY)
      real::      HIPAREV(KX,KY)
      real::      HIPRIV(KX,KY)
      real::      HIPARIV(KX,KY)
      end module

      module M_ATOM_mod
      !use grid_param
	  USE PARAMS
      implicit none
      real::      ALFAV(KX,KY,KZ,KIM)
      real::      BETAV(KX,KY,KZ,KIM)
      real::      GAMAV(KX,KY,KZ,KIM)
      real::      ALFH0V(KX,KY,IG)
      real::      GAMAHV(KX,KY,IG)
      real::      BETAHV(KX,KY)
      end module

      module M_ZRODLA_mod
      !use grid_param
	  USE PARAMS
      implicit none
      real::      SOU0V(KX,KY)
      real::      SOUZ0V(KX,KY,KZ,KIM)
      real::      SOU1N(KX,KY)
      real::      SOUZ1N(KX,KY,KZ,KIM)
      real::      SOUTEV(KX,KY)
      real::      SOUTIV(KX,KY)
      end module

      module M_VISC_mod
      !use grid_param
	  USE PARAMS
      implicit none
      real::      ETAIXV(KX,KY)
      real::      ETAIYV(KX,KY)
      real::      ETAZXV(KX,KY,KZ,KIM)
      real::      ETAZYV(KX,KY,KZ,KIM)
      real::      ETNUMV(KX,KY)
      real::      ETNUMZV(KX,KY,KZ,KIM)
      real::      ETIPERPV(KX,KY)
      real::      ETZPERPV(KX,KY,KZ,KIM)
      end module

      module M_GEOM_mod
      !use grid_param
	  USE PARAMS
      implicit none
      real::      RXN(KX,KY)
      real::      RYN(KX,KY)
      real::      GGN(KX,KY)
      real::      BRATION(KX,KY)
      real::      BTORN(KX,KY)
      real::      BTOTN(KX,KY)
      real::      RZN(KX,KY)
      real::      VIPARN(KX,KY)
      real::      VEPARN(KX,KY)
      real::      VZPARN(KX,KY,KZ,KIM)
      end module

      module M_DRIFT_mod
      !use grid_param
	  USE PARAMS
      implicit none
      real::      PHIPV(KX,KY)
      real::      CURPARN(KX,KY)
      real::      CURDIN(KX,KY)
      real::      VDIIN(KX,KY)
      real::      VDIEN(KX,KY)
      real::      VDIZN(KX,KY,KZ,KIM)
      real::      VRADIN(KX,KY)
      real::      VRADEN(KX,KY)
      real::      VRADZN(KX,KY,KZ,KIM)
      real::      PSI1V(KX,KY)
      real::      PSI2V(KX,KY)
      real::      PSITOTV(KX,KY)
      real::      BFUNV(KX,KY)
      real::      SPSI1N(KX,KY)
      real::      SPSI2N(KX,KY)
      real::      BFUNZV(KX,KY,KZ,KIM)
      real::      SIGMAV(KX,KY)
      real::      OMSTARN(KX,KY)
      real::      OMSTARZN(KX,KY,KZ,KIM)
      end module

      module ELOSS_mod
      !use grid_param
	  USE PARAMS
      implicit none
      real::      PRLINH(KX,KY)
      real::      STJONH(KX,KY)
      real::      PRLIN(KX,KY)
      real::      STJON(KX,KY)
      real::      STJONZI(KX,KY,KIM)
      real::      PRLINI(KX,KY,KIM)
      real::      QLINI(KX,KY,KZ,KIM)
	  REAL::      PQJONZ(KIM)
	  REAL::      PQLINZ(KIM)
	  REAL::      PQJONZT      !FORMER XPQJONZ FROM MODULE OUTHUM_mod
	  REAL::      PQLINZT      !FORMER XPQLINZ FROM MODULE OUTHUM_mod
	  REAL::      PQJONH      !=SUM(STJONH(I,J)*EC*NETE*DVG) OVER I AND J
      end module

      module TEVOL_mod
	  USE PARAMS
      implicit none
      real:: PROMH
      real:: PROMC2
      real:: PROMC3
      real:: PROMZ
      real:: VPLASMAOLD(KT1)
      real:: VIMPUROLD(KIM,(1+3*KZ))
      real:: VPLASMA(KT1)
      real:: VIMPUR(KIM,(1+3*KZ))  !MAX SIZE:5X88, ACTUAL: 1 x (1+3*10) | KIM*(1+3*KZ)
      real:: TPLOLD(4,KY)
      real:: NPLOLD(4,KY)
      integer:: INDEX1
      !integer:: INDEX2
      end module

      module SASIEDZI_mod
      !use grid_param
	  USE PARAMS
      implicit none
      integer::   ISN(KX,KY,4)
      integer::   ISV(KX,KY,4)
      integer::   ISX1     !I-COORDINATE FOR 1ST X-POINT - V-GRID
      integer::   ISX2     !I-COORDINATE FOR 2ND X-POINT - V-GRID
      integer::   ISXN1    !I-COORDINATE FOR 1ST X-POINT
      integer::   ISXN2    !I-COORDINATE FOR 2ND X-POINT
	  !INTEGER::   IPOINT     !CHECKOUT XYSOLVEHVX
      end module

      module DPROF_mod
      !use grid_param
	  USE PARAMS
      implicit none
      real::      DIFCN(KX,KY)
	  real::      DIFCZ(KX,KY)
      real::      DIFCTE(KX,KY)
	  real::      DIFCTI(KX,KY)
      real::      FXPOINT(KX,KY)
      end module

      module BIAS_mod
      !use grid_param
	  USE PARAMS
      implicit none
      real::      CBIAS
      real::      FIBIAS
      real::      CURBIAS(KX,KY)
      end module

      module POLAR_mod
      !use grid_param
	  USE PARAMS
      implicit none
      real::      CUREXT
      real::      CUREXT0
      real::      TUP
      integer::   JCONT
      real::      CUREXTOLD
      real::      PRAD(KY)
      end module

      module PUFFDATA
      !use grid_param
	  USE PARAMS
      implicit none
      real::      SPUFF(KIM) !FORMER PFLUX(KIM)
      real::      XPUFF(KIM)
      real::      PUFFW(KIM)
      real::      T0WALL(KIM)
!CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
!C    XPUFF - POLOIDAL COORDINATE OF THE PUFF CENTER
!C    PUFFW - WIDTH OF THE NEUTRAL SOURCE DUE TO PUFFING
!C    SPUFF - TOTAL PARTICLE FLUX DUE TO PUFFING
!C    T0WALL - INITIAL TEMPERATURE OF NEUTRALS
!CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
      end module

      module PUFF_mod
      !use grid_param
	  USE PARAMS
      implicit none
      real::      VZPUF(KX,KY)
      real::      UZPUF(KX,KY)
      real::      VZPUFPAR(KX,KY)
      real::      NZPUF(KX,KY)
      real::      TZPUF(KX,KY)
      end module

      module VMODELPAR !NOW USED ALSO IN COREDIV SOL
      !use grid_param
      implicit none
      real::      RL1
      real::      RL2
      real::      TEMP0
      real::      DIVANGLE
      end module

      module CONDC_mod
      !use grid_param
	  USE PARAMS
      implicit none
      real::      HIPRE(KX,KY)
      real::      HIPARE(KX,KY)
      real::      HIPRI(KX,KY)
      real::      HIPARI(KX,KY)
      end module

      module M_NEUVEL_mod
      !use grid_param
	  USE PARAMS
      implicit none
      real::      V0PARN(KX,KY,IG)
      real::      V0PERPN(KX,KY,IG)
      real::      U0XN(KX,KY,IG)
      end module

      module PLYTA_mod
      !use grid_param
      implicit none
      real::      FISPUTT
      real::      SPUTFLUX(2,10)   !TODO
      end module

      module POTBIS_mod
      !use grid_param
	  USE PARAMS
      implicit none
      real::      GFI(KX,KY)
      real::      GFZ(KX,KY,KZ,KIM)
      real::      PHISTAR(KY)
      real::      PHIPF(KX,KY)
      real::      ETAIPERP(KX,KY)
      real::      ETAZPERP(KX,KY,KZ,KIM)
      real::      SOUDI1(KX,KY)
      real::      SOUDI2(KX,KY)
      real::      SOUDZ1(KX,KY,KZ,KIM)
      real::      SOUDZ2(KX,KY,KZ,KIM)
      real::      GFI0(KX,KY)
      real::      GFZ0(KX,KY,KZ,KIM)
      end module

      module EQUIL_mod
	  USE PARAMS
      implicit none
      real::      CRN(IDT,KZ,KIM)
      end module

      module ATOM_mod
      !use grid_param
	  USE PARAMS
      implicit none
      real::      ALFA(KX,KY,KZ,KIM)
      real::      BETA(KX,KY,KZ,KIM)
      real::      GAMA(KX,KY,KZ,KIM)
      real::      ALFH0(KX,KY,IG)
      real::      GAMAH(KX,KY,IG)
      real::      BETAH(KX,KY)
      end module

      module EQUILIB_mod
	  USE PARAMS
      implicit none
      real::      RCRN(IDT,KZ,KIM)
      end module

      module MCOOR_mod
      !use grid_param
	  USE PARAMS
      implicit none
      real::      XR(KX1,KY1)
      real::      YR(KX1,KY1)
      real::      RPO(KX1,KY1)
      real::      RTO(KX1,KY1)
      end module

      module OLDD_mod
      !use grid_param
	  USE PARAMS
      implicit none
      real::      CURPOB(KX,KY)
      real::      CURDOB(KX,KY)
      real::      PHIPOB(KX,KY)
      real::      VDIOB(KX,KY)
      real::      VDEOB(KX,KY)
      real::      VDZOB(KX,KY,KZ,KIM)
      real::      VRADIOB(KX,KY)
      real::      VRADEOB(KX,KY)
      real::      VRADZOB(KX,KY,KZ,KIM)
      real::      CURXOB(KX,KY)
      real::      CURYOB(KX,KY)
      real::      PHIPSOLD(KY)
      real::      OMSOB(KX,KY)
      real::      OMSZOB(KX,KY,KZ,KIM)
      end module

      module BISET_mod !TODO
      !use grid_param
      implicit none
      real::      AA0(201)
      real::      AA1(201)
      real::      AA2(201)
      real::      AA3(201)
      real::      AFF1(201)
      real::      AFF2(201)
      real::      AFF2O(201)
      end module

      module VISC_mod
      !use grid_param
	  USE PARAMS
      implicit none
      real::      ETAIX(KX,KY)
      real::      ETAIY(KX,KY)
      real::      ETAZX(KX,KY,KZ,KIM)
      real::      ETAZY(KX,KY,KZ,KIM)
      real::      ETNUM(KX,KY)
      real::      ETNUMZ(KX,KY,KZ,KIM)
      end module

      module LIMIT_mod
      !use grid_param
	  USE PARAMS
      implicit none
      real::      FLIMN(KY)
      real::      FLIMD(KY)
      end module

      module PROFILE_mod
	  USE PARAMS
      !use grid_param
      implicit none
      real::      PROFC(KY)
      end module

      module VF_mod
      !use grid_param
	  USE PARAMS
      implicit none
      real::      VDIAMIF(KX,KY)
      real::      VDIAMEF(KX,KY)
      real::      VDIAMZF(KX,KY,KZ,KIM)
      real::      VRADIF(KX,KY)
      real::      VRADEF(KX,KY)
      real::      VRADZF(KX,KY,KZ,KIM)
      real::      CURXF(KX,KY)
      real::      CURYF(KX,KY)
      real::      CURPARF(KX,KY)
      end module

      module M_SOURCE_mod
      !use grid_param
	  USE PARAMS
      implicit none
      real::      SOUDI1N(KX,KY)
      real::      SOUDI2N(KX,KY)
      real::      SOUDZ1N(KX,KY,KZ,KIM)
      real::      SOUDZ2N(KX,KY,KZ,KIM)
      real::      GFIN(KX,KY)
      real::      GFZN(KX,KY,KZ,KIM)
      end module

      module CURFUNN_mod
      use PARAMS
      implicit none
      integer::   J
      real::      SUM1
      real::      RESTT
      real::      TEES
      real::      TEIS
      real::      FLES
      real::      FLIS
      real::      DRFOLD(KY,2)
      end module

      module SIDEN_mod
      use PARAMS
      implicit none
      real::      FIMPN(KX,KY)
      real::      FEXPN(KX,KY)
      real::      VVN(KX,KY)
      end module

      module DFCOEF_mod
      !use grid_param
	  USE PARAMS
      implicit none
      real::      RDIF(KX,KY)
      real::      RVIF(KX,KY)
      !real::      RDIFZ(KX,KY,KZ,KIM) !SHOULD HAVE IMX+1, IMY+1
      real::      RDIFZ(KX1,KY1,KZ,KIM) !SHOULD HAVE IMX+1, IMY+1
      real::      RVIFZ(KX,KY,KZ,KIM)
      end module

      module NOLD_mod
      !use grid_param
	  USE PARAMS
      implicit none
      real::      DEN(KX,KY)
      real::      DENZ(KX,KY,KZ,KIM)
      end module

      module TEST_mod
      !use grid_param
      implicit none
      real::      EFACTOR
	  real::      STEOR
      end module

!      module ROTATION_mod
!      use grid_param
!      implicit none
!      end module

      module DIFVEL_mod
      use PARAMS
      implicit none
      real::      UDIFI(KX,KY)
      real::      UDIFZ(KX,KY,KZ,KIM)
      end module

      module GBOUND_mod
      !use grid_param
      implicit none
      real::      G(3)
      end module

      module M_LIGHT_mod
      !use grid_param
	  USE PARAMS
      implicit none
      real::      QLINV(KX,KY,KZ)
      end module

      module SIDEV_mod
      !use grid_param
	  USE PARAMS
      implicit none
      real::      FIMPV(KX,KY)
      real::      FEXPV(KX,KY)
      real::      VVV(KX,KY)
      end module

      module COLTIME_mod
      !use grid_param
	  USE PARAMS
      implicit none
      real::      TAUII(KX,KY)
      real::      TAUEE(KX,KY)
      end module

      module M_COLTIME_mod
      !use grid_param
	  USE PARAMS
      implicit none
      real::      TAUIIV(KX,KY)
      real::      TAUEEV(KX,KY)
      end module

      module VELENGTH_mod
      !use grid_param
	  USE PARAMS
      implicit none
      real::      DVLOLD(KY)
      end module

      module BOUND_mod
      implicit none
      real::      A1(2,2)
      real::      B1(2)
      real::      A2(2,2)
      real::      B2(2)
      end module

      module PROGCYC_mod
      !use grid_param
	  USE PARAMS
      implicit none
      real::      AX1(2,2,KY)
      real::      AX2(2,2,KY)
      real::      BX1(2,KY)
      real::      BX2(2,KY)
      end module

      module NPAR_mod
      implicit none
      real::      RECM    !USED AS A PARAMETER
      !real::      RECE    !NEVER USED
      real::      DELT0   !USED AS A PARAMETER
      end module

      module HYDRDYF_mod
      !use grid_param
	  USE PARAMS
      implicit none
      real::      HDYF(KX,KY,IG)
      real::      ETAN0(KX,KY,IG)
      real::      HIN0(KX,KY,IG)
      end module

      module NZRODLA_mod
      !use grid_param
	  USE PARAMS
      implicit none
      real::      SOUH0(KX,KY,IG)
      real::      SOUH1(KX,KY,IG)
      real::      SOUH1N(KX,KY,IG)
      end module

      module ITERATION_mod
      !use grid_param
	  USE PARAMS
      implicit none
      real::      NOLD(KX,KY)
      real::      VOLD(KX,KY)
      end module

      module SIDEHN_mod
      !use grid_param
	  USE PARAMS
      implicit none
      real::      FIMPHN(KX,KY)
      real::      FEXPHN(KX,KY)
      real::      VVHN(KX,KY)
      end module

      module SIDEHV_mod
      !use grid_param
	  USE PARAMS
      implicit none
      real::      FIMPHV(KX,KY)
      real::      FEXPHV(KX,KY)
      real::      HVVV(KX,KY)
      end module

      module TARGET_mod
      !use grid_param
	  USE PARAMS
      implicit none
      real::      ITSTEPS(KY)
      real::      OTSTEPS(KY)
      real::      MIDSTEPS(KY)
      real::      ITDYSTANS(KY)
      real::      OTDYSTANS(KY)
      real::      MIDDYSTANS(KY)
      real::      STEPS(KX,KY)
      real::      DYSTANS(KX,KY)
      real::      DYSTANSPOL(KX,KY)
      real::      ITTE(KY)
      real::      ITNE(KY)
      real::      ITND(KY)
      real::      ITLOAD(KY)
      real::      OTTE(KY)
      real::      OTNE(KY)
      real::      OTND(KY)
      real::      OTLOAD(KY)
      real::      MIDTE(KY)
      real::      MIDNE(KY)
      real::      MIDND(KY)
      real::      ITRSTRIKEPOINT
      real::      OTRSTRIKEPOINT
      real::      MIDRSEPARATRIX
      integer::   INMID
      end module

      module FOROUTPUT_mod
      USE PARAMS, ONLY: KZ, KIM
      implicit none
      real::      NEAV
      real::      TEAV
	  REAL::      NIAV
	  REAL::      TIAV
	  REAL::      NZAV(KZ,KIM)
      real::      ZEFFAV
      real::      CZAV
      real::      AACZAV
	  REAL::      EFFCH
      !real::      NULLPOINT1X
      !real::      NULLPOINT2X
      !real::      NULLPOINT1I
      !real::      NULLPOINT2I
      end module

      module GNUPLOT_mod
      !use grid_param
	  USE PARAMS
      implicit none
      integer::   AGP
      integer::   BGP
      integer::   CGP
      integer::   DGP
      integer::   JJJ
      real::      RGPA(KX,KY)
      real::      RGPB(KX,KY)
      real::      RGPC(KX,KY)
      real::      RGPD(KX,KY)
      real::      ZGPA(KX,KY)
      real::      ZGPB(KX,KY)
      real::      ZGPC(KX,KY)
      real::      ZGPD(KX,KY)
      real::      RGPX
      real::      ZGPX
      end module

	  module OUTHUM_mod
      !use grid_param
	  USE PARAMS
      real::      AMACH(KX,KY)
      real::      COLDEJ(KX,KY)
      real::      COLDEN(KX,KY)
      real::      COLDIJ(KX,KY)
      real::      COLDIN(KX,KY)
      !real::      CONCI(KIM)      !NOT USED
      !real::      CONCE(KIM)      !NOT USED
      !real::      ITDYS           !NOT USED
      !real::      MIDDYS          !NOT USED
      !real::      OTDYS           !NOT USED
      !real::      PROMLIN(KX,KY)  !NOT USED
      real::      PTOT(KX,KY)      !COMPARE PTOT IN TOTALS MODULE
      !real::      PQJONZ(KIM)
      !real::      PQLINZ(KIM)
      real::      QLIN(KX,KY,KZ)   !COMPARE TO QLIN IN LIGHT MODULE
      real::      QQZZ(KX,KY,KZ)
      real::      STRATYE(KX,KY)
      real::      STRATYI(KX,KY)
      real::      STT(KX,KY)
      real::      NZZ(KX,KY,KZ)
      real::      VZZ(KX,KY,KZ)
      real::      UZZ(KX,KY,KZ)
      real::      VPZZ(KX,KY,KZ)
      real::      VDZZ(KX,KY,KZ)
	  real::      SQEINP           !ALSO IN COREDIV SOL
	  real::      SQIINP           !ALSO IN COREDIV SOL
	  real::      SQEWALL          !ALSO IN COREDIV SOL
	  real::      SQIWALL          !ALSO IN COREDIV SOL
	  real::      SQEDIV           !ALSO IN COREDIV SOL
	  real::      SQIDIV           !ALSO IN COREDIV SOL
	  real::      SQEDV1           !ALSO IN COREDIV SOL
      real::      SQIDV1               !ALSO IN COREDIV SOL
      real::      SQEWYCH              !ALSO IN COREDIV SOL
      real::      SQIWYCH              !ALSO IN COREDIV SOL
      real::      EFOUTER 
      real::      EFINNER 
      real::      EFE     
      real::      PVOLE            !ALSO IN COREDIV SOL
      real::      PVOLI            !ALSO IN COREDIV SOL
      real::      PWYME            !ALSO IN COREDIV SOL
      real::      PWYMI            !ALSO IN COREDIV SOL
      real::      VOLE    
      real::      WSK     
      !real::      XSTLIN   
      !real::      XSTLINH  
      !real::      XPQJONH  
      !real::      XPQLINZ
      !real::      XPQJONZ
      real::      FINPUT1         !ALSO IN COREDIV SOL (WITHOUT 1)
      real::      FINPUT2
      real::      FINPUTH
      real::      FBACK            !ALSO IN COREDIV SOL
      real::      FWALL            !ALSO IN COREDIV SOL
      real::      FLIM1            !ALSO IN COREDIV SOL - AS FDIV
      real::      FLIM2  
      real::      SVOL             !ALSO IN COREDIV SOL
      real::      SVOLI  
      real::      SVOLR  
      real::      CURW
      real::      CURE
      real::      CURI
      real::      FINPUTZ1(KIM)
      real::      FINPUTZ2(KIM)
      real::      FINPUTIMP(KIM)
      real::      FBACKZ(KIM)
      real::      FWALLZ(KIM)
      real::      FLIMZ1(KIM)
      real::      FLIMZ2(KIM)
      real::      SVOLZ(KIM)
      real::      SVOLIZ(KIM)
      real::      SVOLRZ(KIM)
      real::      TOTNEUT
      real::      TOTPRESS
      real::      SEPPRESS
      end module

MODULE TRASH !NOT IMPORTANT PARAMETERS, TO BE DECIDED IF TO BE KEPT OR DELETED
  USE PARAMS, ONLY: KX, KY
  IMPLICIT NONE
  !REAL::     SING       !=1 IN INPUTB, FROM MODULE SCLR
  !REAL::     FE(KX)    !(:)=FE0  IN INPUTB
  !REAL::     FI(KX)    !(:)=FI0  IN INPUTB
  REAL::     FE0       !READ FROM IPARSOL IN INPUTB
  REAL::     FI0       !READ FROM IPARSOL IN INPUTB
  REAL::     SOUTE(KX,KY)         !=0. IN ZERO
  REAL::     SOUTI(KX,KY)         !=0. IN ZERO
  REAL::     AMZ
  REAL::     SEPN    !=NSFLUX(LSTZ,L) IN BDNY  (VERY LOCAL!)
  !REAL::     RS       !=RP        IN INPUTB
  REAL::     TAU      !=1.       IN INPUT
  REAL::     STE
  REAL::     STI
  REAL::     ZRECYC   !=ZRECYCC(NAIMI) FROM IMPURPAR - TEMPORARY
  INTEGER::  LNSTOLD  !=LSTNN(INIMI)                 - TEMPORARY
  INTEGER::  LSTOLD   !=ZSRED()+3 OR LNST  IN ZMAX   - TEMPORARY
  INTEGER::  IBRZEG   !READ FROM IPARCORE IN INPUT (IF=2 THEN ONLY SOL)
  INTEGER::  LT       !=250   IN INPUT
  INTEGER::  LT1      !=1     IN INPUT
  INTEGER::  IZAPIS      !READ FROM IPARSOL IN INPUTB
  INTEGER::  LTI         !=IT_STEPS   IN MAIN, BEFORE BRZEG
  REAL::     SUMNE
  REAL::     GDIFA    !
  REAL::     GVINW    !
  !INTEGER::  IHF         !READ FROM IPARSOL IN INPUTB
  REAL::     RMACH     !READ FROM IPARSOL IN INPUTB
  REAL::     EPS0
  !REAL::     SNZ        !=0.00001*STN, =SNZ/AREA  IN INPUTB
  REAL::     STNZ    !=15.E6  IN INPUTB, =0    IN CORE2SOL
  integer::   LITER
  integer::   LITERI
  integer::   ITSUB
END MODULE

 
! ----------------------------------------------

  !    module divsurface_mod
  !    use grid_param
  !    implicit none
  !    !real TDSmax
  !    !real TDSmin
  !    !real TSurf(2,KY+1)
  !    end module

! module CONSTANT_mod
! implicit none
! real, parameter :: PI=3.141592654
! end module

!      module AEFF_mod
!      use grid_param
!      implicit none
!      end module

! MODULE SOURCENE !OK
  ! USE PARAMS
  ! IMPLICIT NONE
  ! REAL::     ZNEJ(KR)   !NOT USED
  ! REAL::     ZNEN(KR)   !NOT USED
! END MODULE

!      module FLUX0_mod
!      use grid_param
!      implicit none
!      end module

!      module KINET_mod !replaced by KINET
!      !use grid_param
!      USE PARAMS, ONLY: BFS
!      implicit none
!      real::      FFE(BFS)
!      real::      FFI(BFS)
!      real::      FFZ(BFS)
!      real::      RMI(BFS)
!      real::      RMZ(BFS)
!      end module

!      module SEPARATRIX_mod
!      use grid_param
!      implicit none
!      real::      NISEP
!      real::      TESEP
!      real::      TISEP
!      end module

      ! module WARIANT_mod
      ! use grid_param
      ! implicit none
      ! !integer::   INH
      ! !integer::   INZ
      ! !integer::   IHF
      ! !integer::   ISTYPE
      ! !integer::   IBCORE
      ! !integer::   IBCOREZ
      ! !real::      ZS
      ! !real::      SPUFF0
      ! !integer::   ISYM
      ! end module

      ! module WARIANT2_mod
      ! use grid_param
      ! implicit none
      ! !integer::   JCASE
      ! !integer::   IREGION     !SEEMS AS IT SHOULD BE A LOCAL VAR
      ! !integer::   IPROMPT
      ! !integer::   IVAPOR
      ! !DOUBLE PRECISION PROGFACT
      ! end module

      ! module SCLR_mod
      ! use grid_param
      ! implicit none
      ! !real::      PI
      ! !real::      EC
      ! !real::      XEM
      ! !real::      XMI
      ! !real::      ZM
      ! !real::      AMU
      ! !real::      AMZ
      ! !real::      SING
      ! !real::      CONCIMP
      ! !integer::   JVEND    !MOVED TO NET_MOD
      ! !real::      YEND     !MADE LOCAL IN XYSIATKA
      ! end module

!      module HANDYVAR_mod
!      implicit none
!      real::      DINLET
!      end module

!MODULE XPUFF !OK
!  USE PARAMS
!  IMPLICIT NONE
!  REAL::     ZS(KIM)       !READ FROM IPARSOL IN INPUTB, THEN *XK
!  REAL::     SPUFF(KIM)    !READ FROM IPARSOL IN INPUTB
!  REAL::     YPUFF(KIM)    !READ FROM IPARSOL IN INPUTB, THEN *XK
!  REAL::     TWALL         !=3.     IN INPUTB
!END MODULE

!      module INIT_mod
!      use grid_param
!      implicit none
!      real::      NE0
!      real::      NEK
!      real::      TI0
!      real::      TE0
!      real::      TIK
!      real::      TEK
!      real::      N0K
!      end module

!      module IOPN_mod
!      use grid_param
!      implicit none
!      !integer::   IOPNE
!      !integer::   IOPNI
!      !integer::   IOPTE
!      !integer::   IOPTI
!      !integer::   IOPV
!      !integer::   IOPN0
!      !integer::   IOPNET
!      !integer::   IOPNZ
!      !integer::   IOPVZ
!      !integer::   IOPZEF
!      integer::   IORIENT
!      end module

!      module RADIAT_mod !ATOM DATA FOR LINE RADIATION OF IMPURITIES
!      use grid_param
!      implicit none
!      !real::      PLIN(IDT,KZ,KIM)
!      end module

!      module IMPURITY_mod !ATOM DATA FOR IMPURITIES (IONOZATION, RECOMBINATION..)
!      use grid_param
!      implicit none
!      real::      ALFF(IDT,KZ,KIM)
!      real::      BETT(IDT,KZ,KIM)
!      real::      GAMM(IDT,KZ,KIM)
!      real::      POTJON(KZ,KIM)
!      real::      PLIN(IDT,KZ,KIM)
!      end module

!      module POT_mod !ATOM DATA FOR IONIZATION POTENTIAL FOR IMPURITIES
!      use grid_param
!      implicit none
!      !real::      POTJON(KZ,KIM)
!      end module

!      module WODOR_mod !ATOM DATA FOR HYDROGEN
!      use grid_param
!      implicit none
!      real::      ALFW(IDT)
!      real::      BETW(IDT)
!      real::      GAMW(IDT)
!      end module

!      module RADIAL_mod
!      use grid_param
!      implicit none
!      !real::      RT
!      !real::      RP
!      !real::      RS       !REPLACED BY RS FROM DEVICE MODULE
!	  !real::      BT
!      !real::      BTAV     !CALCULATED IN MAGCOORD_NEW, NOT USED IN TECXY
!      !real::      Q        !CALCULATED IN MAGCOORD_NEW, NOT USED IN TECXY
!      !real::      GAMAD   !NOT USED BESIDE INITIALIZATION
!      !real::      GAMAW   !NOT USED BESIDE INITIALIZATION
!      !real::      TDIFA
!      !real::      TVINW
!      !real::      TDIFH
!      !real::      TVINH
!      !real::      TETAY0
!      !real::      TCONDE
!      !real::      TCONDI
!      !real::      TDIFE
!      !real::      AREA
!      !integer::   ILZER
!      !real::      TOTCUR
!      !real::      DL
!      end module

!      module BOUNDARY_mod
!      use grid_param
!      implicit none
!      !real::      YLAMN
!      !real::      YLAMTE
!      !real::      YLAMTI
!      !real::      DNSEPI
!      !real::      DNSEPZ
!      end module

! module NET_mod
! use PARAMS
! implicit none
! !real::      XP
! !real::      XS
! !real::      XK
! !real::      YP
! !real::      YK
! !real::      YTRANS
! !integer::   IMX
! !integer::   IMY
! !real::      X(KX1)
! !real::      Y(KY1)
! !integer::   JLINE
! !integer::   JVEND
! !real::      DL       !CALCULATED IN MAGCOORD_NEW
! !real::      AREA     !CALCULATED IN MAGCOORD_NEW, BUT OVERWRITTEN FROM CORE
! end module

!      module NEUVEL_mod
!      !use grid_param
!	  USE PARAMS
!      implicit none
!      !real::      V0PAR(KX,KY,IG)
!      !real::      V0PERP(KX,KY,IG)
!      !real::      U0X(KX,KY,IG)
!      end module

!      module PLASMA_mod
!      !use grid_param !KX=131,KY=71,IG=5
!	  USE PARAMS
!      implicit none
!      !real::      NE(KX,KY)
!      !real::      NI(KX,KY)
!      !real::      TE(KX,KY)
!      !real::      TI(KX,KY)
!      !real::      VI(KX,KY)
!      !real::      UI(KX,KY)
!      !real::      V0(KX,KY,IG)
!      !real::      U0(KX,KY,IG)
!      !real::      ZEFF(KX,KY)
!      !real::      ELF(KX,KY)
!      !real::      VE(KX,KY)
!      !real::      UE(KX,KY)
!      !real::      CURX(KX,KY)
!      !real::      CURY(KX,KY)
!      !real::      NITOT(KX,KY)
!      !real::      T0(KX,KY,IG)
!      !real::      N0(KX,KY,IG)
!      !real::      TZ0(KX,KY,KIM)
!      end module

!      module folders_mod
!      implicit none
!      !character*200 dsrd
!      !character*100 rundir,atomdir,meshdir,dwnloaddir
!                    !,headdir,progdir,tokname, tokcase
!      end module

!module iofiles_mod
!  implicit none
!  character*50 texevolfl!, &
!               !texdryffl, texiparfl, xymesh, texwynikfl,texidatfl
!  !INTEGER, PARAMETER:: ndwnlfls = 18
!  !character dwnlfls(ndwnlfls)*15
!  !!real::      dwnlfls(ndwnlfls)
!  !data dwnlfls /'iondens','eledens','iontemp','eletemp', &
!  ! 'plavpar','plavpol','hyd1dens','hyd2dens','hyd1temp', &
!  ! 'hyd2temp','ionpress','elepress','ionloss','eleloss','lineloss', &
!  ! 'proftgt1','proftgt2','profmidpl'/
!end module

!      module PRES_mod
!      !use grid_param
!	  USE PARAMS
!      implicit none
!      real::      PII(KX,KY)
!      real::      PEE(KX,KY)
!      end module

!      module ZRODLA_mod
!      !use grid_param
!	  USE PARAMS
!      implicit none
!      !real::      SOU0(KX,KY)
!      !real::      SOUZ0(KX,KY,KZ,KIM)
!      !real::      SOU1(KX,KY)
!      !real::      SOUZ1(KX,KY,KZ,KIM)
!      !real::      SOUTE(KX,KY)
!      !real::      SOUTI(KX,KY)
!      end module

!MODULE BTX !OK
!  USE PARAMS
!  IMPLICIT NONE
!  REAL::     PRMI(KY)        !=f()               IN BOUNDCF
!  REAL::     PRMZ(KY,KZ,KIM) !=f()               IN BOUNDCF
!  REAL::     PFE(KY)         !RFUN(XXX, FFE)-2.5 IN BOUNDCF
!  REAL::     PFI(KY)         !RFUN(XXX, FFI)-2.5 IN BOUNDCF
!  REAL::     PFZ(KY,KZ,KIM)  !=f()               IN BOUNDCF
!END MODULE

!      module GEOMETRY_mod
!      !use grid_param
!	  USE PARAMS
!      implicit none
!      !real::      RX(KX,KY)
!      !real::      RY(KX,KY)
!      !real::      GG(KX,KY)
!      !real::      BRATIO(KX,KY)
!      !real::      BTOR(KX,KY)
!      !real::      BTOT(KX,KY)
!      !real::      RZ(KX,KY)
!      !real::      VIPAR(KX,KY)
!      !real::      VEPAR(KX,KY)
!      !real::      VZPAR(KX,KY,KZ,KIM)
!      end module

!      module STER_mod
!      !use grid_param
!      implicit none
!      !integer::   LTI      !REPLACED BY IT_STEPS
!      !integer::   LWYD     !DUPLICATED IN WARIANT
!      !integer::   IZAPIS   !NOT USED
!      !integer::   IMODEL
!      !integer::   IPRINT
!      !integer::   LITER    !TBR
!      !integer::   LITERI   !TBR
!      !integer::   ITSUB    !replaced by NESMOD
!      !real::      DNES0
!      !REAL::      XYBLADP  !MOVED TO EVOL
!      !REAL::      XYBLADZ  !MOVED TO EVOL
!      !REAL::      EPSP
!      !REAL::      EPSZ
!      end module

!module grid_param
!  implicit none
!  !integer, parameter :: KX=131,KY=71,KZ=88,KIM=4
!  !integer, parameter :: KX1=KX+1, KY1=KY+1
!  !integer, parameter :: IDT=500   !KX2=132,KY2=72,  IG=5
!  !integer, parameter :: KT1=200,KT2=20000
!  !INTEGER, PARAMETER:: ndwnlfls = 18   !!!!!!!!!!!!!!!!
!end module